# syntax = docker/dockerfile:1.4.3


####################################
#                                  #
# LABSIM-DEVCONTAINER-GCC-BOOKWORM #
#                                  #
# ================================ #
# -> labsim-base-gcc-bookworm      #
####################################


# multi stage build
FROM labsim-base-gcc-bookworm as labsim-devcontainer-gcc-bookworm

# RUN sh -c 'if ! cpanm < /dev/null > /dev/null 2>&1 ; then curl -L http://cpanmin.us | perl - App::cpanminus; fi'

# prettifyng
LABEL description="LABSIM devcontainer distro - Linux Debian 12 & GNU GCC 14.1.0" \
      maintainer="nawfel.kinani@onera.fr" \
      version="2.0.1" \
      org.name="ONERA" \
      org.department="DTIS" \
      org.unit="ICNA" \
      org.laboratory="LABSIM" \
      org.center="Salon-de-Provence" \
      license="GNU GPLv3"

#
# mandatory argument : GAIA + user
#
ARG GAIA_TARGET_ECOSYSTEM="2.0.1"
ARG GAIA_ENABLE_FEATURE="dev,sb,sf"
ARG USERNAME=labsim
ARG USER_UID=1000
ARG USER_GID=$USER_UID

#
# Create the labsim dev user
#
RUN groupadd --gid $USER_GID $USERNAME \
   && useradd --uid $USER_UID --gid $USER_GID --create-home --shell /bin/bash --no-log-init $USERNAME \
   #
   # Add sudo support (Omit if you don't need to install software after connecting.)
   #
   && apt-get update \
   && apt-get install -y sudo \
   && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
   && chmod 0440 /etc/sudoers.d/$USERNAME

#
# setup LABSIM Simulation Software Ecosysten : create dir, clone sources from github, then integrate gaia features & VSCode workspace
#
WORKDIR /home/$USERNAME/dev

#
# mount build secrets
#
RUN --mount=type=secret,mode=0444,id=GITHUB_USERNAME,required=true \
    --mount=type=secret,mode=0444,id=GITHUB_TOKEN,required=true \
    #
    # clone LABSIM repositories
    #
    git clone --recurse-submodules https://$(cat /run/secrets/GITHUB_USERNAME):$(cat /run/secrets/GITHUB_TOKEN)@github.com/LABSIM/GAIA.git titans/GAIA \
 && git clone --recurse-submodules https://$(cat /run/secrets/GITHUB_USERNAME):$(cat /run/secrets/GITHUB_TOKEN)@github.com/LABSIM/OURANOS.git titans/OURANOS \
 && git clone --recurse-submodules https://$(cat /run/secrets/GITHUB_USERNAME):$(cat /run/secrets/GITHUB_TOKEN)@github.com/LABSIM/THETYS.git titans/THETYS \
 && git clone --recurse-submodules https://$(cat /run/secrets/GITHUB_USERNAME):$(cat /run/secrets/GITHUB_TOKEN)@github.com/LABSIM/OCEAN.git titans/OCEAN \
 && git clone --recurse-submodules https://$(cat /run/secrets/GITHUB_USERNAME):$(cat /run/secrets/GITHUB_TOKEN)@github.com/LABSIM/RHEA.git titans/RHEA \
 && git clone --recurse-submodules https://$(cat /run/secrets/GITHUB_USERNAME):$(cat /run/secrets/GITHUB_TOKEN)@github.com/LABSIM/KRONOS.git titans/KRONOS \
    #
    # finally, bootstrap GAIA
    #
 && cd titans/GAIA \
 && chmod +x GAIA-bootstrap \
 && ./GAIA-bootstrap --verbosity-level info --target-ecosystem ${GAIA_TARGET_ECOSYSTEM} --enable-feature ${GAIA_ENABLE_FEATURE}

#
# inject the LABSIM SSE VSCode workspace
#
COPY distro/labsim/docker/labsim.code-workspace .

#
# give all access to labsim
#
RUN \
    chown -R $USERNAME /home/$USERNAME \
 && chgrp -R $USERNAME /home/$USERNAME

#
# Set the default user (Omit if you want to keep the default as root.)
#
USER $USERNAME
