#!/bin/bash

#
# GAIA : required LABSIM ground software ecosystem
# Copyright (C) 2012-2016  Nawfel KINANI
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.
# If not, see <http://www.gnu.org/licenses/>.
#

#######################
# Progiciels environment config
#
# Ce fichier defini les variables necessaires aux 
# different Progiciels 
#
# 07/02/12 - Kinani Nawfel

# configuration DRI ?
if [ -z ${GAIA_FOUND_DRI_HOST+x} ]; then 
	# LABSIM HOST
	NEED_DRI_BYPASS_HACK=0
else 
	# DRI HOST
	NEED_DRI_BYPASS_HACK=1
fi

if [ $NEED_DRI_BYPASS_HACK -ne 1 ]; then

	###################################################################
	# MPC
	###

	MPC_ROOT=$PRO_HOME/mpc-$MPC_VERSION
	MPC_LIBRARYDIR=$MPC_ROOT/lib
	MPC_INCLUDEDIR=$MPC_ROOT/include

	export MPC_ROOT MPC_LIBRARYDIR MPC_INCLUDEDIR

	###################################################################
	# MPFR
	###

	MPFR_ROOT=$PRO_HOME/mpfr-$MPFR_VERSION
	MPFR_LIBRARYDIR=$MPFR_ROOT/lib
	MPFR_INCLUDEDIR=$MPFR_ROOT/include

	export MPFR_ROOT MPFR_LIBRARYDIR MPFR_INCLUDEDIR

	###################################################################
	# GMP
	###

	GMP_ROOT=$PRO_HOME/gmp-$GMP_VERSION
	GMP_LIBRARYDIR=$GMP_ROOT/lib
	GMP_INCLUDEDIR=$GMP_ROOT/include

	export GMP_ROOT GMP_LIBRARYDIR GMP_INCLUDEDIR

	###################################################################
	# AutoGen
	###

	AUTOGEN_ROOT=$PRO_HOME/autogen-$AUTOGEN_VERSION
	AUTOGEN_BINARYDIR=$AUTOGEN_ROOT/bin
	AUTOGEN_LIBRARYDIR=$AUTOGEN_ROOT/lib
	AUTOGEN_INCLUDEDIR=$AUTOGEN_ROOT/include

	export AUTOGEN_ROOT AUTOGEN_BINARYDIR AUTOGEN_LIBRARYDIR AUTOGEN_INCLUDEDIR

	###################################################################
	# GCC
	###

	GCC_ROOT=$PRO_HOME/gcc-$GCC_VERSION
	GCC_BINARYDIR=$GCC_ROOT/bin
	GCC_LIBRARYDIR=$GCC_ROOT/lib
	GCC_LIBRARY64DIR=$GCC_ROOT/lib64
	GCC_LIBRARYEXECDIR=$GCC_ROOT/libexec/gcc/x86_64-unknown-linux-gnu/$GCC_VERSION
	GCC_INCLUDEDIR=$GCC_ROOT/include

	CC=$GCC_BINARYDIR/gcc
	CXX=$GCC_BINARYDIR/g++

	export GCC_ROOT GCC_BINARYDIR GCC_LIBRARYDIR GCC_LIBRARY64DIR GCC_LIBRARYEXECDIR GCC_INCLUDEDIR CC CXX

fi # DRI ?

###################################################################
# PERL
###

PERL_ROOT=$PRO_HOME/perl-$PERL_VERSION
PERL_BINARYDIR=$PERL_ROOT/bin

export PERL_ROOT PERL_BINARYDIR

###################################################################
# Doxygen
###

DOXYGEN_ROOT=$PRO_HOME/doxygen-$DOXYGEN_VERSION
DOXYGEN_BINARYDIR=$DOXYGEN_ROOT/bin

export DOXYGEN_ROOT DOXYGEN_BINARYDIR

###################################################################
# Xerces-C++
###

XERCESC_ROOT=$PRO_HOME/xercesc-$XERCESC_VERSION
XERCESC_BINARYDIR=$XERCESC_ROOT/bin
XERCESC_LIBRARYDIR=$XERCESC_ROOT/lib
XERCESC_INCLUDEDIR=$XERCESC_ROOT/include

export XERCESC_ROOT XERCESC_BINARYDIR XERCESC_LIBRARYDIR XERCESC_INCLUDEDIR

###################################################################
# GLM
###

GLM_ROOT=$PRO_HOME/glm-$GLM_VERSION
GLM_INCLUDEDIR=$GLM_ROOT/include

export GLM_ROOT GLM_INCLUDEDIR

###################################################################
# GLFW
###

GLFW_ROOT=$PRO_HOME/glfw-$GLFW_VERSION
GLFW_INCLUDEDIR=$GLFW_ROOT/include
GLFW_LIBRARYDIR=$GLFW_ROOT/lib

export GLFW_ROOT GLFW_INCLUDEDIR GLFW_LIBRARYDIR

###################################################################
# CMake/Ctest/CPack
###

CMAKE_ROOT=$PRO_HOME/cmake-$CMAKE_VERSION
CMAKE_BINARYDIR=$CMAKE_ROOT/bin
CMAKE_MODULE_PATH=$CMAKE_ROOT/share/cmake-$CMAKE_MAJ_VER.$CMAKE_MIN_VER/Modules

export CMAKE_ROOT CMAKE_BINARYDIR CMAKE_MODULE_PATH

###################################################################
# Boost
###

BOOST_ROOT=$PRO_HOME/boost-$BOOST_VERSION
BOOST_LIBRARYDIR=$BOOST_ROOT/lib
BOOST_INCLUDEDIR=$BOOST_ROOT/include

export BOOST_ROOT BOOST_INCLUDEDIR BOOST_LIBRARYDIR

###################################################################
# OpenSceneGraph
###

OSG_ROOT=$PRO_HOME/osg-$OSG_VERSION
OSG_INCLUDEDIR=$OSG_ROOT/include
OSG_LIBRARYDIR=$OSG_ROOT/lib64
OSG_BINARYDIR=$OSG_ROOT/bin

OSG_BDT=${BDD_HOME}/Bdt/
for path in $(find -L ${OSG_BDT} -maxdepth 1 -type d ! -name Bdt); do
	OSG_BDT=$OSG_BDT:$path
done

OSG_TEXTURE=${BDD_HOME}/Texture/
for path in $(find -L ${OSG_TEXTURE} -type d ! -name Texture); do
	OSG_TEXTURE=$OSG_TEXTURE:$path
done

OSG_DYNAMIC=${BDD_HOME}/Dynamic/
for path in $(find -L ${OSG_DYNAMIC} -type d ! -name Dynamic); do
	OSG_DYNAMIC=$OSG_DYNAMIC:$path
done

OSG_STATIC=${BDD_HOME}/Static/
for path in $(find -L ${OSG_STATIC} -type d ! -name Static); do
	OSG_STATIC=$OSG_STATIC:$path
done

OSG_FILE_PATH=$OSG_BDT:$OSG_TEXTURE:$OSG_DYNAMIC:$OSG_STATIC:$BDD_HOME/INSTRUMENT:$BDD_HOME/IMAGES_PA
OSG_NOTIFY_LEVEL=NOTICE
OSG_OPTIMIZER="DEFAULT ~MAKE_FAST_GEOMETRY"

export OSG_ROOT OSG_INCLUDEDIR OSG_LIBRARYDIR OSG_BINARYDIR OSG_BDT OSG_TEXTURE OSG_DYNAMIC OSG_STATIC OSG_FILE_PATH OSG_NOTIFY_LEVEL OSG_OPTIMIZER

###################################################################
# SilverLining
###

SILVERLINING_ROOT=$PRO_HOME/silverlining-$SILVERLINING_VERSION
SILVERLINING_INCLUDEDIR=$SILVERLINING_ROOT/Public\ Headers
SILVERLINING_LIBRARYDIR=$SILVERLINING_ROOT/lib/linux

SILVERLINING_DIR=$SILVERLINING_ROOT
SILVERLINING_PATH=$SILVERLINING_ROOT/Resources

export SILVERLINING_ROOT SILVERLINING_INCLUDEDIR SILVERLINING_LIBRARYDIR SILVERLINING_DIR SILVERLINING_PATH

###################################################################
# FFTSS
###

FFTSS_ROOT=$PRO_HOME/fftss-$FFTSS_VERSION
FFTSS_BINARYDIR=$FFTSS_ROOT/bin
FFTSS_LIBRARYDIR=$FFTSS_ROOT/lib
FFTSS_INCLUDEDIR=$FFTSS_ROOT/include

export FFTSS_ROOT FFTSS_BINARYDIR FFTSS_LIBRARYDIR FFTSS_INCLUDEDIR 

###################################################################
# Triton
###

TRITON_ROOT=$PRO_HOME/triton-$TRITON_VERSION
TRITON_INCLUDEDIR=$TRITON_ROOT/Public\ Headers
TRITON_LIBRARYDIR=$TRITON_ROOT/lib/Linux/x64

TRITON_DIR=$TRITON_ROOT
TRITON_PATH=$TTRITON_ROOT/Resources

export TRITON_ROOT TRITON_INCLUDEDIR TRITON_LIBRARYDIR TRITON_DIR TRITON_PATH

###################################################################
# OpenCV
###

OPENCV_ROOT=$PRO_HOME/opencv-$OPENCV_VERSION
OPENCV_LIBRARYDIR=$OPENCV_ROOT/lib
OPENCV_INCLUDEDIR=$OPENCV_ROOT/include
OPENCV_BINARYDIR=$OPENCV_ROOT/bin

export OPENCV_ROOT OPENCV_INCLUDEDIR OPENCV_LIBRARYDIR OPENCV_BINARYDIR

###################################################################
# HID API
###

HIDAPI_ROOT=$PRO_HOME/hidapi-$HIDAPI_VERSION
HIDAPI_LIBRARYDIR=$HIDAPI_ROOT/lib
HIDAPI_INCLUDEDIR=$HIDAPI_ROOT/include

export HIDAPI_ROOT HIDAPI_INCLUDEDIR HIDAPI_LIBRARYDIR

###################################################################
# JSON CPP
###

JSONCPP_ROOT=$PRO_HOME/jsoncpp-$JSONCPP_VERSION
JSONCPP_LIBRARYDIR=$JSONCPP_ROOT/lib
JSONCPP_INCLUDEDIR=$JSONCPP_ROOT/include

export JSONCPP_ROOT JSONCPP_INCLUDEDIR JSONCPP_LIBRARYDIR

###################################################################
# OSVR - lib functionality
###

OSVR_LIBFUNCTIONALITY_ROOT=$PRO_HOME/osvr-libfunctionality-$OSVR_LIBFUNCTIONALITY_VERSION
OSVR_LIBFUNCTIONALITY_LIBRARYDIR=$OSVR_LIBFUNCTIONALITY_ROOT/lib64
OSVR_LIBFUNCTIONALITY_INCLUDEDIR=$OSVR_LIBFUNCTIONALITY_ROOT/include
OSVR_LIBFUNCTIONALITY_BINARYDIR=$OSVR_LIBFUNCTIONALITY_ROOT/bin

export OSVR_LIBFUNCTIONALITY_ROOT OSVR_LIBFUNCTIONALITY_INCLUDEDIR OSVR_LIBFUNCTIONALITY_LIBRARYDIR OSVR_LIBFUNCTIONALITY_BINARYDIR

###################################################################
# OSVR - core
###

OSVR_CORE_ROOT=$PRO_HOME/osvr-core-$OSVR_CORE_VERSION
OSVR_CORE_LIBRARYDIR=$OSVR_CORE_ROOT/lib64
OSVR_CORE_INCLUDEDIR=$OSVR_CORE_ROOT/include
OSVR_CORE_BINARYDIR=$OSVR_CORE_ROOT/bin

export OSVR_CORE_ROOT OSVR_CORE_INCLUDEDIR OSVR_CORE_LIBRARYDIR OSVR_CORE_BINARYDIR

###################################################################
# QT
###

QT_ROOT=$PRO_HOME/qt-$QT_VERSION
QT_INCLUDEDIR=$QT_ROOT/include
QT_LIBRARYDIR=$QT_ROOT/lib
QT_BINARYDIR=$QT_ROOT/bin

QTEMBEDDED_ROOT=$QT_ROOT/libembedded-widget
QTEMBEDDED_INCLUDEDIR=$QTEMBEDDED_ROOT/include
QTEMBEDDED_LIBRARYDIR=$QTEMBEDDED_ROOT/lib

QTDIR=$QT_ROOT
QTINC=$QT_INCLUDEDIR
QTLIB=$QT_LIBRARYDIR

export QT_ROOT QT_INCLUDEDIR QT_LIBRARYDIR QT_BINARYDIR QTEMBEDDED_ROOT QTEMBEDDED_INCLUDEDIR QTEMBEDDED_LIBRARYDIR QTDIR QTINC QTLIB

###################################################################
# CEGUI
###

CEGUI_ROOT=$PRO_HOME/cegui-$CEGUI_VERSION
CEGUI_BINARYDIR=$CEGUI_ROOT/bin
CEGUI_LIBRARYDIR=$CEGUI_ROOT/lib
CEGUI_INCLUDEDIR=$CEGUI_ROOT/include

export CEGUI_ROOT CEGUI_BINARYDIR CEGUI_LIBRARYDIR CEGUI_INCLUDEDIR

###################################################################
# CEED
###
#
#CEED_ROOT=$PRO_HOME/ceed-$CEED_VERSION
#CEED_BINARYDIR=$CEED_ROOT/bin
#CEED_LIBRARYDIR=$CEED_ROOT/lib
#
#export CEED_ROOT CEED_BINARYDIR CEED_LIBRARYDIR

###################################################################
# Leap Motion SDK
###
#
#LEAPMOTION_ROOT=$PRO_HOME/Leap_Developer_Kit_$LEAPMOTION_VERSION
#LEAPMOTION_LIBRARYDIR=$LEAPMOTION_ROOT/LeapSDK/lib
#LEAPMOTION_INCLUDEDIR=$LEAPMOTION_ROOT/LeapSDK/include
#
#export LEAPMOTION_ROOT LEAPMOTION_LIBRARYDIR LEAPMOTION_INCLUDEDIR

###################################################################
# QT Creator
###

QTCREATOR_ROOT=$PRO_HOME/qt-creator-$QTCREATOR_VERSION
QTCREATOR_LIBRARYDIR=$QTCREATOR_ROOT/lib
QTCREATOR_BINARYDIR=$QTCREATOR_ROOT/bin

export QTCREATOR_ROOT QTCREATOR_LIBRARYDIR QTCREATOR_BINARYDIR

###################################################################
# Global Variable
###

# is it a DRI administrated host
if [ $NEED_DRI_BYPASS_HACK -ne 1 ]; then
	GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* mpc v.$MPC_VERSION"
	GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* mpfr v.$MPFR_VERSION"
	GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* gmp v.$GMP_VERSION"
	GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* autogen v.$AUTOGEN_VERSION"
	GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* gcc v.$GCC_VERSION"
fi # DRI ?
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* perl v.$PERL_VERSION"
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* doxygen v.$DOXYGEN_VERSION"
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* xercesc v.$XERCESC_VERSION"
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* glm v.$GLM_VERSION"
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* glfw v.$GLFW_VERSION"
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* cmake v.$CMAKE_VERSION"
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* boost v.$BOOST_VERSION"
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* osg v.$OSG_VERSION"
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* silverlining v.$SILVERLINING_VERSION"
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* fftss v.$FFTSS_VERSION"
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* triton v.$TRITON_VERSION"
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* opencv v.$OPENCV_VERSION"
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* hid api v.$HIDAPI_VERSION"
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* jsonccpp v.$JSONCPP_VERSION"
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* osvr-libfunctionality v.$OSVR_LIBFUNCTIONALITY_VERSION"
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* osvr-core v.$OSVR_CORE_VERSION"
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* cegui v.$CEGUI_VERSION"
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* qt v.$QT_VERSION"
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* qt-creator v.$QTCREATOR_VERSION"
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* opensplicedds v.$OSPL_VERSION"
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* adobe flash player v.$ADOBEFLASHPLAYER_VERSION"
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* firefox v.$FIREFOX_VERSION"
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* jre v.$JRE_VERSION"
GAIA_DEV_DIST="$GAIA_DEV_DIST\n\t|\t* eclipse v.$ECLIPSE_VERSION"

# configuration DRI ?
if [ $NEED_DRI_BYPASS_HACK -ne 1 ]; then

	# prepone the new GCC to inhibit the installed one 

CPATH=$GCC_INCLUDEDIR\
:$QT_INCLUDEDIR\
:$MPC_INCLUDEDIR\
:$MPFR_INCLUDEDIR\
:$GMP_INCLUDEDIR\
:$AUTOGEN_INCLUDEDIR\
:$XERCESC_INCLUDEDIR\
:$GLFW_INCLUDEDIR\
:$OSG_INCLUDEDIR\
:$SILVERLINING_INCLUDEDIR\
:$FFTSS_INCLUDEDIR\
:$TRITON_INCLUDEDIR\
:$OPENCV_INCLUDEDIR\
:$HIDAPI_INCLUDEDIR\
:$JSONCPP_INCLUDEDIR\
:$OSVR_LIBFUNCTIONALITY_INCLUDEDIR\
:$OSVR_CORE_INCLUDEDIR\
:$BOOST_INCLUDEDIR\
:$NVTT_INCLUDEDIR\
:$CEGUI_INCLUDEDIR\
:$CPATH
#:$CEED_LIBRARYDIR\

PATH=$GCC_BINARYDIR\
:$GCC_LIBRARYEXECDIR\
:$PERL_BINARYDIR\
:$QT_BINARYDIR\
:$QTCREATOR_BINARYDIR\
:$CMAKE_BINARYDIR\
:$DOXYGEN_BINARYDIR\
:$PATH\
:$AUTOGEN_BINARYDIR\
:$XERCESC_BINARYDIR\
:$NVTT_BINARYDIR\
:$FFTSS_BINARYDIR\
:$OSG_BINARYDIR\
:$OPENCV_BINARYDIR\
:$OSVR_LIBFUNCTIONALITY_BINARYDIR\
:$OSVR_CORE_BINARYDIR\
:$CEGUI_BINARYDIR
#:$CEED_BINARYDIR

LD_LIBRARY_PATH=$GCC_LIBRARYDIR\
:$GCC_LIBRARY64DIR\
:$QT_LIBRARYDIR\
:$QTCREATOR_LIBRARYDIR\
:$LD_LIBRARY_PATH\
:$MPC_LIBRARYDIR\
:$MPFR_LIBRARYDIR\
:$GMP_LIBRARYDIR\
:$AUTOGEN_LIBRARYDIR\
:$XERCESC_LIBRARYDIR\
:$GLFW_LIBRARYDIR\
:$OSG_LIBRARYDIR\
:$SILVERLINING_LIBRARYDIR\
:$FFTSS_LIBRARYDIR\
:$TRITON_LIBRARYDIR\
:$OPENCV_LIBRARYDIR\
:$HIDAPI_LIBRARYDIR\
:$JSONCPP_LIBRARYDIR\
:$OSVR_LIBFUNCTIONALITY_LIBRARYDIR\
:$OSVR_CORE_LIBRARYDIR\
:$BOOST_LIBRARYDIR\
:$NVTT_LIBRARYDIR\
:$CEGUI_LIBRARYDIR
#:$CEED_LIBRARYDIR\
#:$LEAPMOTION_LIBRARYDIR
	
else
	
CPATH=$QT_INCLUDEDIR\
:$XERCESC_INCLUDEDIR\
:$GLFW_INCLUDEDIR\
:$OSG_INCLUDEDIR\
:$SILVERLINING_INCLUDEDIR\
:$FFTSS_INCLUDEDIR\
:$TRITON_INCLUDEDIR\
:$OPENCV_INCLUDEDIR\
:$HIDAPI_INCLUDEDIR\
:$JSONCPP_INCLUDEDIR\
:$OSVR_LIBFUNCTIONALITY_INCLUDEDIR\
:$OSVR_CORE_INCLUDEDIR\
:$BOOST_INCLUDEDIR\
:$NVTT_INCLUDEDIR\
:$CEGUI_INCLUDEDIR\
:$CPATH
#:$CEED_LIBRARYDIR\

PATH=$PERL_BINARYDIR\
:$QT_BINARYDIR\
:$QTCREATOR_BINARYDIR\
:$CMAKE_BINARYDIR\
:$DOXYGEN_BINARYDIR\
:$PATH\
:$AUTOGEN_BINARYDIR\
:$XERCESC_BINARYDIR\
:$NVTT_BINARYDIR\
:$FFTSS_BINARYDIR\
:$OSG_BINARYDIR\
:$OPENCV_BINARYDIR\
:$OSVR_LIBFUNCTIONALITY_BINARYDIR\
:$OSVR_CORE_BINARYDIR\
:$CEGUI_BINARYDIR
#:$CEED_BINARYDIR

LD_LIBRARY_PATH=$QT_LIBRARYDIR\
:$QTCREATOR_LIBRARYDIR\
:$LD_LIBRARY_PATH\
:$XERCESC_LIBRARYDIR\
:$GLFW_LIBRARYDIR\
:$OSG_LIBRARYDIR\
:$SILVERLINING_LIBRARYDIR\
:$FFTSS_LIBRARYDIR\
:$TRITON_LIBRARYDIR\
:$OPENCV_LIBRARYDIR\
:$JSONCPP_LIBRARYDIR\
:$HIDAPI_LIBRARYDIR\
:$OSVR_LIBFUNCTIONALITY_LIBRARYDIR\
:$OSVR_CORE_LIBRARYDIR\
:$BOOST_LIBRARYDIR\
:$NVTT_LIBRARYDIR\
:$CEGUI_LIBRARYDIR
#:$CEED_LIBRARYDIR\
#:$LEAPMOTION_LIBRARYDIR

fi # DRI ?

# add Ceed to PYTHONPATH module
#PYTHONPATH=:$CEGUI_ROOT\
#:$CEED_ROOT\
#:$PYTHONPATH

export CPATH PATH LD_LIBRARY_PATH

###################################################################
