#!/bin/bash

#######################
# Progiciels environment config
#
# Ce fichier defini les variables necessaires aux 
# different Progiciels 
#
# 07/02/12 - Kinani Nawfel

# configuration DRI ?
if [ $LABSIM_DRI_HOST_ADMIN -neq 1 ]; then

	###################################################################
	# MPC
	###

	MPC_ROOT=$PRO_HOME/mpc-$MPC_VERSION
	MPC_LIBRARYDIR=$MPC_ROOT/lib
	MPC_INCLUDEDIR=$MPC_ROOT/include

	export MPC_ROOT MPC_LIBRARYDIR MPC_INCLUDEDIR

	###################################################################
	# MPFR
	###

	MPFR_ROOT=$PRO_HOME/mpfr-$MPFR_VERSION
	MPFR_LIBRARYDIR=$MPFR_ROOT/lib
	MPFR_INCLUDEDIR=$MPFR_ROOT/include

	export MPFR_ROOT MPFR_LIBRARYDIR MPFR_INCLUDEDIR

	###################################################################
	# GMP
	###

	GMP_ROOT=$PRO_HOME/gmp-$GMP_VERSION
	GMP_LIBRARYDIR=$GMP_ROOT/lib
	GMP_INCLUDEDIR=$GMP_ROOT/include

	export GMP_ROOT GMP_LIBRARYDIR GMP_INCLUDEDIR

	###################################################################
	# AutoGen
	###

	AUTOGEN_ROOT=$PRO_HOME/autogen-$AUTOGEN_VERSION
	AUTOGEN_BINARYDIR=$AUTOGEN_ROOT/bin
	AUTOGEN_LIBRARYDIR=$AUTOGEN_ROOT/lib
	AUTOGEN_INCLUDEDIR=$AUTOGEN_ROOT/include

	export AUTOGEN_ROOT AUTOGEN_BINARYDIR AUTOGEN_LIBRARYDIR AUTOGEN_INCLUDEDIR

	###################################################################
	# GCC
	###

	GCC_ROOT=$PRO_HOME/gcc-$GCC_VERSION
	GCC_BINARYDIR=$GCC_ROOT/bin
	GCC_LIBRARYDIR=$GCC_ROOT/lib
	GCC_LIBRARY64DIR=$GCC_ROOT/lib64
	GCC_LIBRARYEXECDIR=$GCC_ROOT/libexec/gcc-$GCC_VERSION/x86_64-unknown-linux-gnu/$GCC_VERSION
	GCC_INCLUDEDIR=$GCC_ROOT/include

	CC=$GCC_BINARYDIR/gcc
	CXX=$GCC_BINARYDIR/g++

	export GCC_ROOT GCC_BINARYDIR GCC_LIBRARYDIR GCC_LIBRARY64DIR GCC_LIBRARYEXECDIR GCC_INCLUDEDIR CC CXX

fi # DRI ?

###################################################################
# Doxygen
###

DOXYGEN_ROOT=$PRO_HOME/doxygen-$DOXYGEN_VERSION
DOXYGEN_BINARYDIR=$DOXYGEN_ROOT/bin

export DOXYGEN_ROOT DOXYGEN_BINARYDIR

###################################################################
# Xerces-C++
###

XERCESC_ROOT=$PRO_HOME/xercesc-$XERCESC_VERSION
XERCESC_BINARYDIR=$XERCESC_ROOT/bin
XERCESC_LIBRARYDIR=$XERCESC_ROOT/lib
XERCESC_INCLUDEDIR=$XERCESC_ROOT/include

export XERCESC_ROOT XERCESC_BINARYDIR XERCESC_LIBRARYDIR XERCESC_INCLUDEDIR

###################################################################
# GLM
###

GLM_ROOT=$PRO_HOME/glm-$GLM_VERSION
GLM_INCLUDEDIR=$GLM_ROOT/include

export GLM_ROOT GLM_INCLUDEDIR

###################################################################
# GLFW
###

GLFW_ROOT=$PRO_HOME/glfw-$GLFW_VERSION
GLFW_INCLUDEDIR=$GLFW_ROOT/include
GLFW_LIBRARYDIR=$GLFW_ROOT/lib

export GLFW_ROOT GLFW_INCLUDEDIR GLFW_LIBRARYDIR

###################################################################
# CMake/Ctest/CPack
###

CMAKE_ROOT=$PRO_HOME/cmake-$CMAKE_VERSION
CMAKE_BINARYDIR=$CMAKE_ROOT/bin
CMAKE_MODULE_PATH=$CMAKE_ROOT/share/cmake-$CMAKE_MAJ_VER.$CMAKE_MIN_VER/Modules

export CMAKE_ROOT CMAKE_BINARYDIR CMAKE_MODULE_PATH

###################################################################
# Boost
###

BOOST_ROOT=$PRO_HOME/boost-$BOOST_VERSION
BOOST_LIBRARYDIR=$BOOST_ROOT/lib
BOOST_INCLUDEDIR=$BOOST_ROOT/include

export BOOST_ROOT BOOST_INCLUDEDIR BOOST_LIBRARYDIR

###################################################################
# OpenSceneGraph
###

OSG_ROOT=$PRO_HOME/osg-$OSG_VERSION
OSG_INCLUDEDIR=$OSG_ROOT/include
OSG_LIBRARYDIR=$OSG_ROOT/lib64
OSG_BINARYDIR=$OSG_ROOT/bin

OSG_BDT=${BDD_HOME}/Bdt/
for path in $(find -L ${OSG_BDT} -maxdepth 1 -type d ! -name Bdt); do
	OSG_BDT=$OSG_BDT:$path
done

OSG_TEXTURE=${BDD_HOME}/Texture/
for path in $(find -L ${OSG_TEXTURE} -type d ! -name Texture); do
	OSG_TEXTURE=$OSG_TEXTURE:$path
done

OSG_DYNAMIC=${BDD_HOME}/Dynamic/
for path in $(find -L ${OSG_DYNAMIC} -type d ! -name Dynamic); do
	OSG_DYNAMIC=$OSG_DYNAMIC:$path
done

OSG_STATIC=${BDD_HOME}/Static/
for path in $(find -L ${OSG_STATIC} -type d ! -name Static); do
	OSG_STATIC=$OSG_STATIC:$path
done

OSG_FILE_PATH=$OSG_BDT:$OSG_TEXTURE:$OSG_DYNAMIC:$OSG_STATIC:$BDD_HOME/INSTRUMENT:$BDD_HOME/IMAGES_PA
OSG_NOTIFY_LEVEL=NOTICE
OSG_OPTIMIZER="DEFAULT ~MAKE_FAST_GEOMETRY"

export OSG_ROOT OSG_INCLUDEDIR OSG_LIBRARYDIR OSG_BINARYDIR OSG_BDT OSG_TEXTURE OSG_DYNAMIC OSG_STATIC OSG_FILE_PATH OSG_NOTIFY_LEVEL OSG_OPTIMIZER

###################################################################
# SilverLining
###

SILVERLINING_ROOT=$PRO_HOME/silverlining-$SILVERLINING_VERSION
SILVERLINING_INCLUDEDIR=$SILVERLINING_ROOT/Public\ Headers
SILVERLINING_LIBRARYDIR=$SILVERLINING_ROOT/lib/linux

SILVERLINING_DIR=$SILVERLINING_ROOT
SILVERLINING_PATH=$SILVERLINING_INCLUDEDIR

export SILVERLINING_ROOT SILVERLINING_INCLUDEDIR SILVERLINING_LIBRARYDIR SILVERLINING_DIR SILVERLINING_PATH

###################################################################
# FFTSS
###

FFTSS_ROOT=$PRO_HOME/fftss-$FFTSS_VERSION
FFTSS_BINARYDIR=$FFTSS_ROOT/bin
FFTSS_LIBRARYDIR=$FFTSS_ROOT/lib
FFTSS_INCLUDEDIR=$FFTSS_ROOT/include

export FFTSS_ROOT FFTSS_BINARYDIR FFTSS_LIBRARYDIR FFTSS_INCLUDEDIR 

###################################################################
# Triton
###

TRITON_ROOT=$PRO_HOME/triton-$TRITON_VERSION
TRITON_INCLUDEDIR=$TRITON_ROOT/include
TRITON_LIBRARYDIR=$TRITON_ROOT/lib

TRITON_DIR=$TRITON_ROOT
TRITON_PATH=$TRITON_INCLUDEDIR/Triton

export TRITON_ROOT TRITON_INCLUDEDIR TRITON_LIBRARYDIR TRITON_DIR TRITON_PATH

###################################################################
# QT
###

QT_ROOT=$PRO_HOME/qt-$QT_VERSION
QT_INCLUDEDIR=$QT_ROOT/include
QT_LIBRARYDIR=$QT_ROOT/lib
QT_BINARYDIR=$QT_ROOT/bin

QTEMBEDDED_ROOT=$QT_ROOT/libembedded-widget
QTEMBEDDED_INCLUDEDIR=$QTEMBEDDED_ROOT/include
QTEMBEDDED_LIBRARYDIR=$QTEMBEDDED_ROOT/lib

QTDIR=$QT_ROOT
QTINC=$QT_INCLUDEDIR
QTLIB=$QT_LIBRARYDIR

export QT_ROOT QT_INCLUDEDIR QT_LIBRARYDIR QT_BINARYDIR QTEMBEDDED_ROOT QTEMBEDDED_INCLUDEDIR QTEMBEDDED_LIBRARYDIR QTDIR QTINC QTLIB

###################################################################
# QT Creator
###

QTCREATOR_ROOT=$PRO_HOME/qt-creator-$QTCREATOR_VERSION
QTCREATOR_INCLUDEDIR=$QTCREATOR_ROOT/include
QTCREATOR_LIBRARYDIR=$QTCREATOR_ROOT/lib
QTCREATOR_BINARYDIR=$QTCREATOR_ROOT/bin

export QTCREATOR_ROOT QTCREATOR_INCLUDEDIR QTCREATOR_LIBRARYDIR QTCREATOR_BINARYDIR

###################################################################
# CEGUI
###

CEGUI_ROOT=$PRO_HOME/cegui-$CEGUI_VERSION
CEGUI_BINARYDIR=$CEGUI_ROOT/bin
CEGUI_LIBRARYDIR=$CEGUI_ROOT/lib
CEGUI_INCLUDEDIR=$CEGUI_ROOT/include

export CEGUI_ROOT CEGUI_BINARYDIR CEGUI_LIBRARYDIR CEGUI_INCLUDEDIR

###################################################################
# CEED
###
#
#CEED_ROOT=$PRO_HOME/ceed-$CEED_VERSION
#CEED_BINARYDIR=$CEED_ROOT/bin
#CEED_LIBRARYDIR=$CEED_ROOT/lib
#
#export CEED_ROOT CEED_BINARYDIR CEED_LIBRARYDIR

###################################################################
# Leap Motion SDK
###
#
#LEAPMOTION_ROOT=$PRO_HOME/Leap_Developer_Kit_$LEAPMOTION_VERSION
#LEAPMOTION_LIBRARYDIR=$LEAPMOTION_ROOT/LeapSDK/lib
#LEAPMOTION_INCLUDEDIR=$LEAPMOTION_ROOT/LeapSDK/include
#
#export LEAPMOTION_ROOT LEAPMOTION_LIBRARYDIR LEAPMOTION_INCLUDEDIR

###################################################################
# Global Variable
###

PATH=$QT_BINARYDIR\
:$QTCREATOR_BINARYDIR\
:$CMAKE_BINARYDIR\
:$DOXYGEN_BINARYDIR\
:$PATH\
:$AUTOGEN_BINARYDIR\
:$XERCESC_BINARYDIR\
:$NVTT_BINARYDIR\
:$FFTSS_BINARYDIR\
:$OSG_BINARYDIR\
:$CEGUI_BINARYDIR
#:$CEED_BINARYDIR

# add Ceed to PYTHONPATH module
PYTHONPATH=:$CEGUI_ROOT\
#:$CEED_ROOT\
:$PYTHONPATH

LD_LIBRARY_PATH=$QT_LIBRARYDIR\
:$QTCREATOR_LIBRARYDIR\
:$LD_LIBRARY_PATH\
:$MPC_LIBRARYDIR\
:$MPFR_LIBRARYDIR\
:$GMP_LIBRARYDIR\
:$AUTOGEN_LIBRARYDIR\
:$XERCESC_LIBRARYDIR\
:$GLFW_LIBRARYDIR\
:$OSG_LIBRARYDIR\
:$SILVERLINING_LIBRARYDIR\
:$FFTSS_LIBRARYDIR\
:$TRITON_LIBRARYDIR\
:$BOOST_LIBRARYDIR\
:$NVTT_LIBRARYDIR\
:$CEGUI_LIBRARYDIR
#:$CEED_LIBRARYDIR\
#:$LEAPMOTION_LIBRARYDIR

# configuration DRI ?
if [ $LABSIM_DRI_HOST_ADMIN -neq 1 ]; then

	# prepone the new GCC to inhibit the installed one 

	PATH=$GCC_BINARYDIR\
	:$GCC_LIBRARYEXECDIR\
	:$PATH

	LD_LIBRARY_PATH=$GCC_LIBRARYDIR\
	:$GCC_LIBRARY64DIR\
	:$LD_LIBRARY_PATH

fi # DRI ?

export PATH PYTHONPATH LD_LIBRARY_PATH

###################################################################
