#!/bin/bash

#
# GAIA : required LABSIM ground software ecosystem
# Copyright (C) 2012-2016  Nawfel KINANI
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.
# If not, see <http://www.gnu.org/licenses/>.
#

#################################################
#
# Target versions files
#
# On place ici chacune des versions des outils que l'on souhaite installer pour LABSIM-1.0.0
#
# (Valentines's Day)
# 14/02/2012 - Kinani Nawfel
#
#################################################

# BINUTILS versions
BINUTILS_INSTALL_TARGET_MAJ_VER=2
BINUTILS_INSTALL_TARGET_MIN_VER=30
BINUTILS_INSTALL_TARGET_PATCH_VER=0
BINUTILS_INSTALL_TARGET_VERSION=${BINUTILS_INSTALL_TARGET_MAJ_VER}.${BINUTILS_INSTALL_TARGET_MIN_VER}.${BINUTILS_INSTALL_TARGET_PATCH_VER}

# GMP versions
GMP_INSTALL_TARGET_MAJ_VER=6
GMP_INSTALL_TARGET_MIN_VER=1
GMP_INSTALL_TARGET_PATCH_VER=2
GMP_INSTALL_TARGET_VERSION=${GMP_INSTALL_TARGET_MAJ_VER}.${GMP_INSTALL_TARGET_MIN_VER}.${GMP_INSTALL_TARGET_PATCH_VER}

# MPFR versions
MPFR_INSTALL_TARGET_MAJ_VER=4
MPFR_INSTALL_TARGET_MIN_VER=0
MPFR_INSTALL_TARGET_PATCH_VER=1
MPFR_INSTALL_TARGET_VERSION=${MPFR_INSTALL_TARGET_MAJ_VER}.${MPFR_INSTALL_TARGET_MIN_VER}.${MPFR_INSTALL_TARGET_PATCH_VER}

# MPC versions
MPC_INSTALL_TARGET_MAJ_VER=1
MPC_INSTALL_TARGET_MIN_VER=1
MPC_INSTALL_TARGET_PATCH_VER=0
MPC_INSTALL_TARGET_VERSION=${MPC_INSTALL_TARGET_MAJ_VER}.${MPC_INSTALL_TARGET_MIN_VER}.${MPC_INSTALL_TARGET_PATCH_VER}

# AUTOGEN versions
AUTOGEN_INSTALL_TARGET_MAJ_VER=5
AUTOGEN_INSTALL_TARGET_MIN_VER=18
AUTOGEN_INSTALL_TARGET_PATCH_VER=4
AUTOGEN_INSTALL_TARGET_VERSION=${AUTOGEN_INSTALL_TARGET_MAJ_VER}.${AUTOGEN_INSTALL_TARGET_MIN_VER}.${AUTOGEN_INSTALL_TARGET_PATCH_VER}

# ISL versions
ISL_INSTALL_TARGET_MAJ_VER=0
ISL_INSTALL_TARGET_MIN_VER=19
ISL_INSTALL_TARGET_PATCH_VER=0
ISL_INSTALL_TARGET_VERSION=${ISL_INSTALL_TARGET_MAJ_VER}.${ISL_INSTALL_TARGET_MIN_VER}.${ISL_INSTALL_TARGET_PATCH_VER}

# GCC versions
GCC_INSTALL_TARGET_MAJ_VER=7
GCC_INSTALL_TARGET_MIN_VER=3
GCC_INSTALL_TARGET_PATCH_VER=0
GCC_INSTALL_TARGET_VERSION=${GCC_INSTALL_TARGET_MAJ_VER}.${GCC_INSTALL_TARGET_MIN_VER}.${GCC_INSTALL_TARGET_PATCH_VER}

# GDB versions
GDB_INSTALL_TARGET_MAJ_VER=8
GDB_INSTALL_TARGET_MIN_VER=1
GDB_INSTALL_TARGET_PATCH_VER=0
GDB_INSTALL_TARGET_VERSION=${GDB_INSTALL_TARGET_MAJ_VER}.${GDB_INSTALL_TARGET_MIN_VER}.${GDB_INSTALL_TARGET_PATCH_VER}

#== EOF
