#!/bin/bash

#
# GAIA : required LABSIM ground software ecosystem
# Copyright (C) 2012-2016  Nawfel KINANI
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.
# If not, see <http://www.gnu.org/licenses/>.
#

# HID API versions
HIDAPI_INSTALL_TARGET_MAJ_VER=0
HIDAPI_INSTALL_TARGET_MIN_VER=8
HIDAPI_INSTALL_TARGET_PATCH_VER=0
HIDAPI_INSTALL_TARGET_VERSION=${HIDAPI_INSTALL_TARGET_MAJ_VER}.${HIDAPI_INSTALL_TARGET_MIN_VER}.${HIDAPI_INSTALL_TARGET_PATCH_VER}

# JSONCPP versions
JSONCPP_INSTALL_TARGET_MAJ_VER=1
JSONCPP_INSTALL_TARGET_MIN_VER=7
JSONCPP_INSTALL_TARGET_PATCH_VER=5
JSONCPP_INSTALL_TARGET_VERSION=${JSONCPP_INSTALL_TARGET_MAJ_VER}.${JSONCPP_INSTALL_TARGET_MIN_VER}.${JSONCPP_INSTALL_TARGET_PATCH_VER}

# VRPN versions
VRPN_INSTALL_TARGET_MAJ_VER=0
VRPN_INSTALL_TARGET_MIN_VER=7
VRPN_INSTALL_TARGET_PATCH_VER=34
VRPN_INSTALL_TARGET_VERSION=${VRPN_INSTALL_TARGET_MAJ_VER}.${VRPN_INSTALL_TARGET_MIN_VER}.${VRPN_INSTALL_TARGET_PATCH_VER}

# OSVR lib functionality versions
OSVR_LIBFUNCTIONALITY_INSTALL_TARGET_MAJ_VER=0
OSVR_LIBFUNCTIONALITY_INSTALL_TARGET_MIN_VER=1
OSVR_LIBFUNCTIONALITY_INSTALL_TARGET_PATCH_VER=0
OSVR_LIBFUNCTIONALITY_INSTALL_TARGET_VERSION=${OSVR_LIBFUNCTIONALITY_INSTALL_TARGET_MAJ_VER}.${OSVR_LIBFUNCTIONALITY_INSTALL_TARGET_MIN_VER}.${OSVR_LIBFUNCTIONALITY_INSTALL_TARGET_PATCH_VER}

# OSVR core versions
OSVR_CORE_INSTALL_TARGET_MAJ_VER=0
OSVR_CORE_INSTALL_TARGET_MIN_VER=6
OSVR_CORE_INSTALL_TARGET_PATCH_VER=0
OSVR_CORE_INSTALL_TARGET_VERSION=${OSVR_CORE_INSTALL_TARGET_MAJ_VER}.${OSVR_CORE_INSTALL_TARGET_MIN_VER}.${OSVR_CORE_INSTALL_TARGET_PATCH_VER}

# OSVR display versions
OSVR_DISPLAY_INSTALL_TARGET_MAJ_VER=0
OSVR_DISPLAY_INSTALL_TARGET_MIN_VER=1
OSVR_DISPLAY_INSTALL_TARGET_PATCH_VER=0
OSVR_DISPLAY_INSTALL_TARGET_VERSION=${OSVR_DISPLAY_INSTALL_TARGET_MAJ_VER}.${OSVR_DISPLAY_INSTALL_TARGET_MIN_VER}.${OSVR_DISPLAY_INSTALL_TARGET_PATCH_VER}

# OSVR tracker viewer versions
OSVR_TRACKER_INSTALL_TARGET_MAJ_VER=0
OSVR_TRACKER_INSTALL_TARGET_MIN_VER=1
OSVR_TRACKER_INSTALL_TARGET_PATCH_VER=0
OSVR_TRACKER_INSTALL_TARGET_VERSION=${OSVR_TRACKER_INSTALL_TARGET_MAJ_VER}.${OSVR_TRACKER_INSTALL_TARGET_MIN_VER}.${OSVR_TRACKER_INSTALL_TARGET_PATCH_VER}

# OSVR Leap Motion plugin versions
OSVR_LEAPMOTION_INSTALL_TARGET_MAJ_VER=0
OSVR_LEAPMOTION_INSTALL_TARGET_MIN_VER=1
OSVR_LEAPMOTION_INSTALL_TARGET_PATCH_VER=0
OSVR_LEAPMOTION_INSTALL_TARGET_VERSION=${OSVR_LEAPMOTION_INSTALL_TARGET_MAJ_VER}.${OSVR_LEAPMOTION_INSTALL_TARGET_MIN_VER}.${OSVR_LEAPMOTION_INSTALL_TARGET_PATCH_VER}

#== EOF
