#!/bin/bash

#
# GAIA : required LABSIM ground software ecosystem
# Copyright (C) 2012-2016  Nawfel KINANI
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.
# If not, see <http://www.gnu.org/licenses/>.
#

# Perl versions
PERL_INSTALL_TARGET_MAJ_VER=5
PERL_INSTALL_TARGET_MIN_VER=26
PERL_INSTALL_TARGET_PATCH_VER=1
PERL_INSTALL_TARGET_VERSION=${PERL_INSTALL_TARGET_MAJ_VER}.${PERL_INSTALL_TARGET_MIN_VER}.${PERL_INSTALL_TARGET_PATCH_VER}

# CMAKE versions
CMAKE_INSTALL_TARGET_MAJ_VER=3
CMAKE_INSTALL_TARGET_MIN_VER=11
CMAKE_INSTALL_TARGET_PATCH_VER=0
CMAKE_INSTALL_TARGET_VERSION=$CMAKE_INSTALL_TARGET_MAJ_VER.$CMAKE_INSTALL_TARGET_MIN_VER.$CMAKE_INSTALL_TARGET_PATCH_VER

# Xerces-C++ versions
XERCESC_INSTALL_TARGET_MAJ_VER=3
XERCESC_INSTALL_TARGET_MIN_VER=2
XERCESC_INSTALL_TARGET_PATCH_VER=1
XERCESC_INSTALL_TARGET_VERSION=${XERCESC_INSTALL_TARGET_MAJ_VER}.${XERCESC_INSTALL_TARGET_MIN_VER}.${XERCESC_INSTALL_TARGET_PATCH_VER}

# Doxygen versions
DOXYGEN_INSTALL_TARGET_MAJ_VER=1
DOXYGEN_INSTALL_TARGET_MIN_VER=8
DOXYGEN_INSTALL_TARGET_PATCH_VER=14
DOXYGEN_INSTALL_TARGET_VERSION=${DOXYGEN_INSTALL_TARGET_MAJ_VER}.${DOXYGEN_INSTALL_TARGET_MIN_VER}.${DOXYGEN_INSTALL_TARGET_PATCH_VER}

# Boost versions
BOOST_INSTALL_TARGET_MAJ_VER=1
BOOST_INSTALL_TARGET_MIN_VER=67
BOOST_INSTALL_TARGET_PATCH_VER=0
BOOST_INSTALL_TARGET_VERSION=${BOOST_INSTALL_TARGET_MAJ_VER}.${BOOST_INSTALL_TARGET_MIN_VER}.${BOOST_INSTALL_TARGET_PATCH_VER}

#== EOF
