#!/bin/bash

#
# GAIA : required LABSIM ground software ecosystem
# Copyright (C) 2012-2016  Nawfel KINANI
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.
# If not, see <http://www.gnu.org/licenses/>.
#

#################################################
#
# Target versions files
#
# On place ici chacune des versions des outils que l'on souhaite installer 
#
# (Valentines's Day)
# 14/02/2012 - Kinani Nawfel
#
#################################################

#===============================================#

# BINUTILS versions
BINUTILS_INSTALL_TARGET_MAJ_VER=@BINUTILS_MAJ_VER@
BINUTILS_INSTALL_TARGET_MIN_VER=@BINUTILS_MIN_VER@
BINUTILS_INSTALL_TARGET_PATCH_VER=@BINUTILS_PATCH_VER@
BINUTILS_INSTALL_TARGET_VERSION=${BINUTILS_INSTALL_TARGET_MAJ_VER}.${BINUTILS_INSTALL_TARGET_MIN_VER}.${BINUTILS_INSTALL_TARGET_PATCH_VER}

# GMP versions
GMP_INSTALL_TARGET_MAJ_VER=@GMP_PATCH_VER@
GMP_INSTALL_TARGET_MIN_VER=@GMP_PATCH_VER@
GMP_INSTALL_TARGET_PATCH_VER=@GMP_PATCH_VER@
GMP_INSTALL_TARGET_VERSION=${GMP_INSTALL_TARGET_MAJ_VER}.${GMP_INSTALL_TARGET_MIN_VER}.${GMP_INSTALL_TARGET_PATCH_VER}

# MPFR versions
MPFR_INSTALL_TARGET_MAJ_VER=@MPFR_PATCH_VER@
MPFR_INSTALL_TARGET_MIN_VER=@MPFR_PATCH_VER@
MPFR_INSTALL_TARGET_PATCH_VER=@MPFR_PATCH_VER@
MPFR_INSTALL_TARGET_VERSION=${MPFR_INSTALL_TARGET_MAJ_VER}.${MPFR_INSTALL_TARGET_MIN_VER}.${MPFR_INSTALL_TARGET_PATCH_VER}

# MPC versions
MPC_INSTALL_TARGET_MAJ_VER=@MPC_PATCH_VER@
MPC_INSTALL_TARGET_MIN_VER=@MPC_PATCH_VER@
MPC_INSTALL_TARGET_PATCH_VER=@MPC_PATCH_VER@
MPC_INSTALL_TARGET_VERSION=${MPC_INSTALL_TARGET_MAJ_VER}.${MPC_INSTALL_TARGET_MIN_VER}.${MPC_INSTALL_TARGET_PATCH_VER}

# AUTOGEN versions
AUTOGEN_INSTALL_TARGET_MAJ_VER=@AUTOGEN_PATCH_VER@
AUTOGEN_INSTALL_TARGET_MIN_VER=@AUTOGEN_PATCH_VER@
AUTOGEN_INSTALL_TARGET_PATCH_VER=@AUTOGEN_PATCH_VER@
AUTOGEN_INSTALL_TARGET_VERSION=${AUTOGEN_INSTALL_TARGET_MAJ_VER}.${AUTOGEN_INSTALL_TARGET_MIN_VER}.${AUTOGEN_INSTALL_TARGET_PATCH_VER}

# ISL versions
ISL_INSTALL_TARGET_MAJ_VER=@ISL_PATCH_VER@
ISL_INSTALL_TARGET_MIN_VER=@ISL_PATCH_VER@
ISL_INSTALL_TARGET_PATCH_VER=@ISL_PATCH_VER@
ISL_INSTALL_TARGET_VERSION=${ISL_INSTALL_TARGET_MAJ_VER}.${ISL_INSTALL_TARGET_MIN_VER}.${ISL_INSTALL_TARGET_PATCH_VER}

# GCC versions
GCC_INSTALL_TARGET_MAJ_VER=@GCC_PATCH_VER@
GCC_INSTALL_TARGET_MIN_VER=@GCC_PATCH_VER@
GCC_INSTALL_TARGET_PATCH_VER=@GCC_PATCH_VER@
GCC_INSTALL_TARGET_VERSION=${GCC_INSTALL_TARGET_MAJ_VER}.${GCC_INSTALL_TARGET_MIN_VER}.${GCC_INSTALL_TARGET_PATCH_VER}

# GDB versions
GDB_INSTALL_TARGET_MAJ_VER=@GDB_PATCH_VER@
GDB_INSTALL_TARGET_MIN_VER=@GDB_PATCH_VER@
GDB_INSTALL_TARGET_PATCH_VER=@GDB_PATCH_VER@
GDB_INSTALL_TARGET_VERSION=${GDB_INSTALL_TARGET_MAJ_VER}.${GDB_INSTALL_TARGET_MIN_VER}.${GDB_INSTALL_TARGET_PATCH_VER}

# Perl versions
PERL_INSTALL_TARGET_MAJ_VER=@PERL_PATCH_VER@
PERL_INSTALL_TARGET_MIN_VER=@PERL_PATCH_VER@
PERL_INSTALL_TARGET_PATCH_VER=@PERL_PATCH_VER@
PERL_INSTALL_TARGET_VERSION=${PERL_INSTALL_TARGET_MAJ_VER}.${PERL_INSTALL_TARGET_MIN_VER}.${PERL_INSTALL_TARGET_PATCH_VER}

# CMAKE versions
CMAKE_INSTALL_TARGET_MAJ_VER=@CMAKE_PATCH_VER@
CMAKE_INSTALL_TARGET_MIN_VER=@CMAKE_PATCH_VER@
CMAKE_INSTALL_TARGET_PATCH_VER=@CMAKE_PATCH_VER@
CMAKE_INSTALL_TARGET_VERSION=$CMAKE_INSTALL_TARGET_MAJ_VER.$CMAKE_INSTALL_TARGET_MIN_VER.$CMAKE_INSTALL_TARGET_PATCH_VER

# Xerces-C++ versions
XERCESC_INSTALL_TARGET_MAJ_VER=@XERCESC_PATCH_VER@
XERCESC_INSTALL_TARGET_MIN_VER=@XERCESC_PATCH_VER@
XERCESC_INSTALL_TARGET_PATCH_VER=@XERCESC_PATCH_VER@
XERCESC_INSTALL_TARGET_VERSION=${XERCESC_INSTALL_TARGET_MAJ_VER}.${XERCESC_INSTALL_TARGET_MIN_VER}.${XERCESC_INSTALL_TARGET_PATCH_VER}

# Doxygen versions
DOXYGEN_INSTALL_TARGET_MAJ_VER=@DOXYGEN_PATCH_VER@
DOXYGEN_INSTALL_TARGET_MIN_VER=@DOXYGEN_PATCH_VER@
DOXYGEN_INSTALL_TARGET_PATCH_VER=@DOXYGEN_PATCH_VER@
DOXYGEN_INSTALL_TARGET_VERSION=${DOXYGEN_INSTALL_TARGET_MAJ_VER}.${DOXYGEN_INSTALL_TARGET_MIN_VER}.${DOXYGEN_INSTALL_TARGET_PATCH_VER}

# Boost versions
BOOST_INSTALL_TARGET_MAJ_VER=@BOOST_PATCH_VER@
BOOST_INSTALL_TARGET_MIN_VER=@BOOST_PATCH_VER@
BOOST_INSTALL_TARGET_PATCH_VER=@BOOST_PATCH_VER@
BOOST_INSTALL_TARGET_VERSION=${BOOST_INSTALL_TARGET_MAJ_VER}.${BOOST_INSTALL_TARGET_MIN_VER}.${BOOST_INSTALL_TARGET_PATCH_VER}

# QT versions
QT_INSTALL_TARGET_MAJ_VER=@QT_PATCH_VER@
QT_INSTALL_TARGET_MIN_VER=@QT_PATCH_VER@
QT_INSTALL_TARGET_PATCH_VER=@QT_PATCH_VER@
QT_INSTALL_TARGET_VERSION=$QT_INSTALL_TARGET_MAJ_VER.$QT_INSTALL_TARGET_MIN_VER.$QT_INSTALL_TARGET_PATCH_VER

# QT Creator versions
QTCREATOR_INSTALL_TARGET_MAJ_VER=@QTCREATOR_PATCH_VER@
QTCREATOR_INSTALL_TARGET_MIN_VER=@QTCREATOR_PATCH_VER@
QTCREATOR_INSTALL_TARGET_PATCH_VER=@QTCREATOR_PATCH_VER@
QTCREATOR_INSTALL_TARGET_VERSION=$QTCREATOR_INSTALL_TARGET_MAJ_VER.$QTCREATOR_INSTALL_TARGET_MIN_VER.$QTCREATOR_INSTALL_TARGET_PATCH_VER

# PROTOBUF versions
PROTOBUF_INSTALL_TARGET_MAJ_VER=@PROTOBUF_PATCH_VER@
PROTOBUF_INSTALL_TARGET_MIN_VER=@PROTOBUF_PATCH_VER@
PROTOBUF_INSTALL_TARGET_PATCH_VER=@PROTOBUF_PATCH_VER@
PROTOBUF_INSTALL_TARGET_VERSION=${PROTOBUF_INSTALL_TARGET_MAJ_VER}.${PROTOBUF_INSTALL_TARGET_MIN_VER}.${PROTOBUF_INSTALL_TARGET_PATCH_VER}

# GRPC versions
GRPC_INSTALL_TARGET_MAJ_VER=@GRPC_PATCH_VER@
GRPC_INSTALL_TARGET_MIN_VER=@GRPC_PATCH_VER@
GRPC_INSTALL_TARGET_PATCH_VER=@GRPC_PATCH_VER@
GRPC_INSTALL_TARGET_VERSION=${GRPC_INSTALL_TARGET_MAJ_VER}.${GRPC_INSTALL_TARGET_MIN_VER}.${GRPC_INSTALL_TARGET_PATCH_VER}

# gSOAP versions
GSOAP_INSTALL_TARGET_MAJ_VER=@GSOAP_PATCH_VER@
GSOAP_INSTALL_TARGET_MIN_VER=@GSOAP_PATCH_VER@
GSOAP_INSTALL_TARGET_PATCH_VER=@GSOAP_PATCH_VER@
GSOAP_INSTALL_TARGET_VERSION=$GSOAP_INSTALL_TARGET_MAJ_VER.$GSOAP_INSTALL_TARGET_MIN_VER.$GSOAP_INSTALL_TARGET_PATCH_VER

# OpenSpliceDDS versions
OSPL_INSTALL_TARGET_MAJ_VER=@OSPL_PATCH_VER@
OSPL_INSTALL_TARGET_MIN_VER=@OSPL_PATCH_VER@
OSPL_INSTALL_TARGET_PATCH_VER=@OSPL_PATCH_VER@
OSPL_INSTALL_TARGET_VERSION=$OSPL_INSTALL_TARGET_MAJ_VER.$OSPL_INSTALL_TARGET_MIN_VER.$OSPL_INSTALL_TARGET_PATCH_VER

# OpenSceneGraph versions
OSG_INSTALL_TARGET_MAJ_VER=@OSG_PATCH_VER@
OSG_INSTALL_TARGET_MIN_VER=@OSG_PATCH_VER@
OSG_INSTALL_TARGET_PATCH_VER=@OSG_PATCH_VER@
OSG_INSTALL_TARGET_VERSION=${OSG_INSTALL_TARGET_MAJ_VER}.${OSG_INSTALL_TARGET_MIN_VER}.${OSG_INSTALL_TARGET_PATCH_VER}

# SilverLining versions
SILVERLINING_INSTALL_TARGET_MAJ_VER=@SILVERLINING_PATCH_VER@
SILVERLINING_INSTALL_TARGET_MIN_VER=@SILVERLINING_PATCH_VER@
SILVERLINING_INSTALL_TARGET_PATCH_VER=@SILVERLINING_PATCH_VER@
SILVERLINING_INSTALL_TARGET_VERSION=${SILVERLINING_INSTALL_TARGET_MAJ_VER}.${SILVERLINING_INSTALL_TARGET_MIN_VER}.${SILVERLINING_INSTALL_TARGET_PATCH_VER}

# FFTSS versions
FFTSS_INSTALL_TARGET_MAJ_VER=@FFTSS_PATCH_VER@
FFTSS_INSTALL_TARGET_MIN_VER=@FFTSS_PATCH_VER@
FFTSS_INSTALL_TARGET_PATCH_VER=@FFTSS_PATCH_VER@
FFTSS_INSTALL_TARGET_VERSION=${FFTSS_INSTALL_TARGET_MAJ_VER}.${FFTSS_INSTALL_TARGET_MIN_VER}.${FFTSS_INSTALL_TARGET_PATCH_VER}

# Triton versions
TRITON_INSTALL_TARGET_MAJ_VER=@TRITON_PATCH_VER@
TRITON_INSTALL_TARGET_MIN_VER=@TRITON_PATCH_VER@
TRITON_INSTALL_TARGET_PATCH_VER=@TRITON_PATCH_VER@
TRITON_INSTALL_TARGET_VERSION=${TRITON_INSTALL_TARGET_MAJ_VER}.${TRITON_INSTALL_TARGET_MIN_VER}.${TRITON_INSTALL_TARGET_PATCH_VER}

# CEGUI versions
CEGUI_INSTALL_TARGET_MAJ_VER=@CEGUI_PATCH_VER@
CEGUI_INSTALL_TARGET_MIN_VER=@CEGUI_PATCH_VER@
CEGUI_INSTALL_TARGET_PATCH_VER=@CEGUI_PATCH_VER@
CEGUI_INSTALL_TARGET_VERSION=$CEGUI_INSTALL_TARGET_MAJ_VER.$CEGUI_INSTALL_TARGET_MIN_VER.$CEGUI_INSTALL_TARGET_PATCH_VER

# CEED versions
CEED_INSTALL_TARGET_MAJ_VER=@CEED_PATCH_VER@
CEED_INSTALL_TARGET_MIN_VER=@CEED_PATCH_VER@
CEED_INSTALL_TARGET_PATCH_VER=@CEED_PATCH_VER@
CEED_INSTALL_TARGET_VERSION=$CEED_INSTALL_TARGET_MAJ_VER.$CEED_INSTALL_TARGET_MIN_VER.$CEED_INSTALL_TARGET_PATCH_VER

# OpenCV versions
OPENCV_INSTALL_TARGET_MAJ_VER=@OPENCV_PATCH_VER@
OPENCV_INSTALL_TARGET_MIN_VER=@OPENCV_PATCH_VER@
OPENCV_INSTALL_TARGET_PATCH_VER=@OPENCV_PATCH_VER@
OPENCV_INSTALL_TARGET_VERSION=${OPENCV_INSTALL_TARGET_MAJ_VER}.${OPENCV_INSTALL_TARGET_MIN_VER}.${OPENCV_INSTALL_TARGET_PATCH_VER}

# HID API versions
HIDAPI_INSTALL_TARGET_MAJ_VER=@HIDAPI_PATCH_VER@
HIDAPI_INSTALL_TARGET_MIN_VER=@HIDAPI_PATCH_VER@
HIDAPI_INSTALL_TARGET_PATCH_VER=@HIDAPI_PATCH_VER@
HIDAPI_INSTALL_TARGET_VERSION=${HIDAPI_INSTALL_TARGET_MAJ_VER}.${HIDAPI_INSTALL_TARGET_MIN_VER}.${HIDAPI_INSTALL_TARGET_PATCH_VER}

# JSONCPP versions
JSONCPP_INSTALL_TARGET_MAJ_VER=@JSONCPP_PATCH_VER@
JSONCPP_INSTALL_TARGET_MIN_VER=@JSONCPP_PATCH_VER@
JSONCPP_INSTALL_TARGET_PATCH_VER=@JSONCPP_PATCH_VER@
JSONCPP_INSTALL_TARGET_VERSION=${JSONCPP_INSTALL_TARGET_MAJ_VER}.${JSONCPP_INSTALL_TARGET_MIN_VER}.${JSONCPP_INSTALL_TARGET_PATCH_VER}

# VRPN versions
VRPN_INSTALL_TARGET_MAJ_VER=@VRPN_PATCH_VER@
VRPN_INSTALL_TARGET_MIN_VER=@VRPN_PATCH_VER@
VRPN_INSTALL_TARGET_PATCH_VER=@VRPN_PATCH_VER@
VRPN_INSTALL_TARGET_VERSION=${VRPN_INSTALL_TARGET_MAJ_VER}.${VRPN_INSTALL_TARGET_MIN_VER}.${VRPN_INSTALL_TARGET_PATCH_VER}

# OSVR lib functionality versions
OSVR_LIBFUNCTIONALITY_INSTALL_TARGET_MAJ_VER=@OSVR_LIBFUNCTIONALITY_PATCH_VER@
OSVR_LIBFUNCTIONALITY_INSTALL_TARGET_MIN_VER=@OSVR_LIBFUNCTIONALITY_PATCH_VER@
OSVR_LIBFUNCTIONALITY_INSTALL_TARGET_PATCH_VER=@OSVR_LIBFUNCTIONALITY_PATCH_VER@
OSVR_LIBFUNCTIONALITY_INSTALL_TARGET_VERSION=${OSVR_LIBFUNCTIONALITY_INSTALL_TARGET_MAJ_VER}.${OSVR_LIBFUNCTIONALITY_INSTALL_TARGET_MIN_VER}.${OSVR_LIBFUNCTIONALITY_INSTALL_TARGET_PATCH_VER}

# OSVR core versions
OSVR_CORE_INSTALL_TARGET_MAJ_VER=@OSVR_CORE_PATCH_VER@
OSVR_CORE_INSTALL_TARGET_MIN_VER=@OSVR_CORE_PATCH_VER@
OSVR_CORE_INSTALL_TARGET_PATCH_VER=@OSVR_CORE_PATCH_VER@
OSVR_CORE_INSTALL_TARGET_VERSION=${OSVR_CORE_INSTALL_TARGET_MAJ_VER}.${OSVR_CORE_INSTALL_TARGET_MIN_VER}.${OSVR_CORE_INSTALL_TARGET_PATCH_VER}

# OSVR display versions
OSVR_DISPLAY_INSTALL_TARGET_MAJ_VER=@OSVR_CORE_PATCH_VER@
OSVR_DISPLAY_INSTALL_TARGET_MIN_VER=@OSVR_CORE_PATCH_VER@
OSVR_DISPLAY_INSTALL_TARGET_PATCH_VER=@OSVR_CORE_PATCH_VER@
OSVR_DISPLAY_INSTALL_TARGET_VERSION=${OSVR_DISPLAY_INSTALL_TARGET_MAJ_VER}.${OSVR_DISPLAY_INSTALL_TARGET_MIN_VER}.${OSVR_DISPLAY_INSTALL_TARGET_PATCH_VER}

# OSVR tracker viewer versions
OSVR_TRACKER_INSTALL_TARGET_MAJ_VER=@OSVR_TRACKER_PATCH_VER@
OSVR_TRACKER_INSTALL_TARGET_MIN_VER=@OSVR_TRACKER_PATCH_VER@
OSVR_TRACKER_INSTALL_TARGET_PATCH_VER=@OSVR_TRACKER_PATCH_VER@
OSVR_TRACKER_INSTALL_TARGET_VERSION=${OSVR_TRACKER_INSTALL_TARGET_MAJ_VER}.${OSVR_TRACKER_INSTALL_TARGET_MIN_VER}.${OSVR_TRACKER_INSTALL_TARGET_PATCH_VER}

# OSVR Leap Motion plugin versions
OSVR_LEAPMOTION_INSTALL_TARGET_MAJ_VER=@OSVR_LEAPMOTION_PATCH_VER@
OSVR_LEAPMOTION_INSTALL_TARGET_MIN_VER=@OSVR_LEAPMOTION_PATCH_VER@
OSVR_LEAPMOTION_INSTALL_TARGET_PATCH_VER=@OSVR_LEAPMOTION_PATCH_VER@
OSVR_LEAPMOTION_INSTALL_TARGET_VERSION=${OSVR_LEAPMOTION_INSTALL_TARGET_MAJ_VER}.${OSVR_LEAPMOTION_INSTALL_TARGET_MIN_VER}.${OSVR_LEAPMOTION_INSTALL_TARGET_PATCH_VER}

#== EOF
