#!/bin/bash
#
# Versions files
#
# On place ici chacune des versions des outils utilisés 
#
# (Valentines's Day)
# 14/02/2012 - Kinani Nawfel
#
#################################################

# MPC versions
MPC_MAJ_VER=1
MPC_MIN_VER=0
MPC_REV_VER=2
MPC_VERSION=${MPC_MAJ_VER}.${MPC_MIN_VER}.${MPC_REV_VER}

# MPFR versions
MPFR_MAJ_VER=3
MPFR_MIN_VER=1
MPFR_REV_VER=2
MPFR_VERSION=${MPFR_MAJ_VER}.${MPFR_MIN_VER}.${MPFR_REV_VER}

# GMP versions
GMP_MAJ_VER=6
GMP_MIN_VER=0
GMP_REV_VER=0
GMP_VERSION=${GMP_MAJ_VER}.${GMP_MIN_VER}.${GMP_REV_VER}

# AutoGen versions
AUTOGEN_MAJ_VER=5
AUTOGEN_MIN_VER=18
AUTOGEN_REV_VER=2
AUTOGEN_VERSION=${AUTOGEN_MAJ_VER}.${AUTOGEN_MIN_VER}.${AUTOGEN_REV_VER}

# GCC versions
GCC_MAJ_VER=4
GCC_MIN_VER=8
GCC_REV_VER=2
GCC_VERSION=${GCC_MAJ_VER}.${GCC_MIN_VER}.${GCC_REV_VER}

# CMAKE versions
CMAKE_MAJ_VER=2
CMAKE_MIN_VER=8
CMAKE_REV_VER=12
CMAKE_VERSION=$CMAKE_MAJ_VER.$CMAKE_MIN_VER.$CMAKE_REV_VER

# Boost versions
BOOST_MAJ_VER=1
BOOST_MIN_VER=55
BOOST_REV_VER=0
BOOST_VERSION=${BOOST_MAJ_VER}.${BOOST_MIN_VER}.${BOOST_REV_VER}

# Nvidia Texture Tools versions
NVTT_MAJ_VER=2
NVTT_MIN_VER=0
NVTT_REV_VER=8-1
NVTT_VERSION=${NVTT_MAJ_VER}.${NVTT_MIN_VER}.${NVTT_REV_VER}

# OpenSceneGraph versions
OSG_MAJ_VER=3
OSG_MIN_VER=2
OSG_REV_VER=0
OSG_VERSION=${OSG_MAJ_VER}.${OSG_MIN_VER}.${OSG_REV_VER}

# CEGUI versions
CEGUI_MAJ_VER=0
CEGUI_MIN_VER=8
CEGUI_REV_VER=3
CEGUI_VERSION=$CEGUI_MAJ_VER.$CEGUI_MIN_VER.$CEGUI_REV_VER

# QT versions
QT_MAJ_VER=4
QT_MIN_VER=8
QT_REV_VER=4
QT_VERSION=$QT_MAJ_VER.$QT_MIN_VER.$QT_REV_VER

# LEAPMOTION version 
LEAPMOTION_MAJ_VER=0
LEAPMOTION_MIN_VER=8
LEAPMOTION_REV_VER=0
LEAPMOTION_PATCH_VER=5300
LEAPMOTION_ARCH_VER=Linux
LEAPMOTION_VERSION=${LEAPMOTION_MAJ_VER}.${LEAPMOTION_MIN_VER}.${LEAPMOTION_REV_VER}_${LEAPMOTION_PATCH_VER}_${LEAPMOTION_ARCH_VER}
