#!/bin/bash

# MPC versions
MPC_MAJ_VER=1
MPC_MIN_VER=0
MPC_REV_VER=1
MPC_VERSION=${MPC_MAJ_VER}.${MPC_MIN_VER}.${MPC_REV_VER}

# MPFR versions
MPFR_MAJ_VER=3
MPFR_MIN_VER=1
MPFR_REV_VER=1
MPFR_VERSION=${MPFR_MAJ_VER}.${MPFR_MIN_VER}.${MPFR_REV_VER}

# GMP versions
GMP_MAJ_VER=5
GMP_MIN_VER=0
GMP_REV_VER=5
GMP_VERSION=${GMP_MAJ_VER}.${GMP_MIN_VER}.${GMP_REV_VER}

# AutoGen versions
AUTOGEN_MAJ_VER=5
AUTOGEN_MIN_VER=16
AUTOGEN_REV_VER=2
AUTOGEN_VERSION=${AUTOGEN_MAJ_VER}.${AUTOGEN_MIN_VER}.${AUTOGEN_REV_VER}

# GCC versions
GCC_MAJ_VER=4
GCC_MIN_VER=7
GCC_REV_VER=2
GCC_VERSION=${GCC_MAJ_VER}.${GCC_MIN_VER}.${GCC_REV_VER}

# Boost versions
BOOST_MAJ_VER=1
BOOST_MIN_VER=53
BOOST_REV_VER=0
BOOST_VERSION=${BOOST_MAJ_VER}.${BOOST_MIN_VER}.${BOOST_REV_VER}

# QT versions
QT_MAJ_VER=4
QT_MIN_VER=
QT_REV_VER=
QT_VERSION=${QT_MAJ_VER}

# Nvidia Texture Tools versions
NVTT_MAJ_VER=2
NVTT_MIN_VER=0
NVTT_REV_VER=8-1
NVTT_VERSION=${NVTT_MAJ_VER}.${NVTT_MIN_VER}.${NVTT_REV_VER}

# OpenSceneGraph versions
OSG_MAJ_VER=3
OSG_MIN_VER=0
OSG_REV_VER=1
OSG_VERSION=${OSG_MAJ_VER}.${OSG_MIN_VER}.${OSG_REV_VER}

# JAVA versions
JAVA_MAJ_VER=1
JAVA_MIN_VER=6
JAVA_REV_VER=0
JAVA_PATCH_VER=31
JAVA_VERSION=${JAVA_MAJ_VER}.${JAVA_MIN_VER}.${JAVA_REV_VER}_${JAVA_PATCH_VER}

# ECLIPSE versions
ECLIPSE_MAJ_VER=kepler
ECLIPSE_REV_VER=M7
ECLIPSE_VERSION=${ECLIPSE_MAJ_VER}-${ECLIPSE_REV_VER}

# FIREFOX versions
FIREFOX_MAJ_VER=17
FIREFOX_MIN_VER=0
FIREFOX_REV_VER=0
FIREFOX_VERSION=${FIREFOX_MAJ_VER}.${FIREFOX_MIN_VER}.${FIREFOX_REV_VER}

# THUNDERBIRD versions
THUNDERBIRD_MAJ_VER=17
THUNDERBIRD_MIN_VER=0
THUNDERBIRD_REV_VER=0
THUNDERBIRD_VERSION=${THUNDERBIRD_MAJ_VER}.${THUNDERBIRD_MIN_VER}.${THUNDERBIRD_REV_VER}

# LEAPMOTION version 
LEAPMOTION_MAJ_VER=0
LEAPMOTION_MIN_VER=8
LEAPMOTION_REV_VER=0
LEAPMOTION_PATCH_VER=5300
LEAPMOTION_ARCH_VER=Linux
LEAPMOTION_VERSION=${LEAPMOTION_MAJ_VER}.${LEAPMOTION_MIN_VER}.${LEAPMOTION_REV_VER}_${LEAPMOTION_PATCH_VER}_${LEAPMOTION_ARCH_VER}
