#!/bin/bash

#
# GAIA : required LABSIM ground software ecosystem
# Copyright (C) 2012-2016  Nawfel KINANI
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.
# If not, see <http://www.gnu.org/licenses/>.
#


# detail
GAIA_DISTRIBUTION_DETAIL="$GAIA_DISTRIBUTION_DETAIL\n\t+--[ Third_party : <Simulation (SIM)> ]"

###################################################################
# PROTOBUF
###

if [ "${GAIA_THIRD_PARTY_PROTOBUF_FOUND}" = true ]; then

	# internal
	GAIA_THIRD_PARTY_PROTOBUF_ROOT=$GAIA_THIRD_PARTY_HOME/protobuf-$GAIA_THIRD_PARTY_PROTOBUF_VERSION
	GAIA_THIRD_PARTY_PROTOBUF_LIBRARYDIR=$GAIA_THIRD_PARTY_PROTOBUF_ROOT/lib
	GAIA_THIRD_PARTY_PROTOBUF_INCLUDEDIR=$GAIA_THIRD_PARTY_PROTOBUF_ROOT/include
	GAIA_THIRD_PARTY_PROTOBUF_BINARYDIR=$GAIA_THIRD_PARTY_PROTOBUF_ROOT/bin

	# info
	GAIA_DISTRIBUTION_DETAIL="$GAIA_DISTRIBUTION_DETAIL\n\t|\t* Google Protocol Buffer v.$GAIA_THIRD_PARTY_PROTOBUF_VERSION"

	# env
	CPATH=$GAIA_THIRD_PARTY_PROTOBUF_INCLUDEDIR:$CPATH
	PATH=$GAIA_THIRD_PARTY_PROTOBUF_BINARYDIR:$PATH
	LD_LIBRARY_PATH=$GAIA_THIRD_PARTY_PROTOBUF_LIBRARYDIR:$LD_LIBRARY_PATH
	PKG_CONFIG_PATH=$GAIA_THIRD_PARTY_PROTOBUF_LIBRARYDIR/pkgconfig:$PKG_CONFIG_PATH

	# clean
	unset GAIA_THIRD_PARTY_PROTOBUF_ROOT
	unset GAIA_THIRD_PARTY_PROTOBUF_LIBRARYDIR
	unset GAIA_THIRD_PARTY_PROTOBUF_INCLUDEDIR
	unset GAIA_THIRD_PARTY_PROTOBUF_BINARYDIR

fi

###################################################################
# GRPC
###

if [ "${GAIA_THIRD_PARTY_GRPC_FOUND}" = true ]; then

	# internal
	GAIA_THIRD_PARTY_GRPC_ROOT=$GAIA_THIRD_PARTY_HOME/grpc-$GAIA_THIRD_PARTY_GRPC_VERSION
	GAIA_THIRD_PARTY_GRPC_LIBRARYDIR=$GAIA_THIRD_PARTY_GRPC_ROOT/lib
	GAIA_THIRD_PARTY_GRPC_INCLUDEDIR=$GAIA_THIRD_PARTY_GRPC_ROOT/include
	GAIA_THIRD_PARTY_GRPC_BINARYDIR=$GAIA_THIRD_PARTY_GRPC_ROOT/bin

	# info
	GAIA_DISTRIBUTION_DETAIL="$GAIA_DISTRIBUTION_DETAIL\n\t|\t* Google gRPC v.$GAIA_THIRD_PARTY_GRPC_VERSION"

	# env
	CPATH=$GAIA_THIRD_PARTY_GRPC_INCLUDEDIR:$CPATH
	PATH=$GAIA_THIRD_PARTY_GRPC_BINARYDIR:$PATH
	LD_LIBRARY_PATH=$GAIA_THIRD_PARTY_GRPC_LIBRARYDIR:$LD_LIBRARY_PATH
	PKG_CONFIG_PATH=$GAIA_THIRD_PARTY_GRPC_LIBRARYDIR/pkgconfig:$PKG_CONFIG_PATH

	# clean
	unset GAIA_THIRD_PARTY_GRPC_ROOT
	unset GAIA_THIRD_PARTY_GRPC_LIBRARYDIR
	unset GAIA_THIRD_PARTY_GRPC_INCLUDEDIR
	unset GAIA_THIRD_PARTY_GRPC_BINARYDIR

fi

###################################################################
# GSOAP
###

if [ "${GAIA_THIRD_PARTY_GSOAP_FOUND}" = true ]; then

	# internal
	GAIA_THIRD_PARTY_GSOAP_ROOT=$GAIA_THIRD_PARTY_HOME/gsoap-$GAIA_THIRD_PARTY_GSOAP_VERSION
	GAIA_THIRD_PARTY_GSOAP_LIBRARYDIR=$GAIA_THIRD_PARTY_GSOAP_ROOT/lib
	GAIA_THIRD_PARTY_GSOAP_INCLUDEDIR=$GAIA_THIRD_PARTY_GSOAP_ROOT/include
	GAIA_THIRD_PARTY_GSOAP_BINARYDIR=$GAIA_THIRD_PARTY_GSOAP_ROOT/bin

	# info
	GAIA_DISTRIBUTION_DETAIL="$GAIA_DISTRIBUTION_DETAIL\n\t|\t* gSOAP v.$GAIA_THIRD_PARTY_GSOAP_VERSION"

	# env
	CPATH=$GAIA_THIRD_PARTY_GSOAP_INCLUDEDIR:$CPATH
	PATH=$GAIA_THIRD_PARTY_GSOAP_BINARYDIR:$PATH
	LD_LIBRARY_PATH=$GAIA_THIRD_PARTY_GSOAP_LIBRARYDIR:$LD_LIBRARY_PATH
	PKG_CONFIG_PATH=$GAIA_THIRD_PARTY_GSOAP_LIBRARYDIR/pkgconfig:$PKG_CONFIG_PATH

	# clean
	unset GAIA_THIRD_PARTY_GSOAP_ROOT
	unset GAIA_THIRD_PARTY_GSOAP_LIBRARYDIR
	unset GAIA_THIRD_PARTY_GSOAP_INCLUDEDIR
	unset GAIA_THIRD_PARTY_GSOAP_BINARYDIR

fi

###################################################################
# OpenSpliceDDS
###

if [ "${GAIA_THIRD_PARTY_OSPL_FOUND}" = true ]; then

	# internal
	GAIA_THIRD_PARTY_OSPL_ROOT=$GAIA_THIRD_PARTY_HOME/opensplice-$GAIA_THIRD_PARTY_OSPL_VERSION
	GAIA_THIRD_PARTY_OSPL_LIBRARYDIR=$GAIA_THIRD_PARTY_OSPL_ROOT/lib
	GAIA_THIRD_PARTY_OSPL_INCLUDEDIR=$GAIA_THIRD_PARTY_OSPL_ROOT/include
	GAIA_THIRD_PARTY_OSPL_BINARYDIR=$GAIA_THIRD_PARTY_OSPL_ROOT/bin

	# OpenSpliceDDS daemon configuration
	OSPL_URI=file://$OSPL_CONFPATH/ospl_simulation_conf.xml

	# source release file
	source "$GAIA_THIRD_PARTY_OSPL_ROOT/release.com"

	# info
	GAIA_DISTRIBUTION_DETAIL="$GAIA_DISTRIBUTION_DETAIL\n\t|\t* opensplice v.$GAIA_THIRD_PARTY_OSPL_VERSION"

	# env
	CPATH=$GAIA_THIRD_PARTY_OSPL_INCLUDEDIR:$CPATH
	PATH=$GAIA_THIRD_PARTY_OSPL_BINARYDIR:$PATH
	LD_LIBRARY_PATH=$GAIA_THIRD_PARTY_OSPL_LIBRARYDIR:$LD_LIBRARY_PATH
	PKG_CONFIG_PATH=$GAIA_THIRD_PARTY_OSPL_LIBRARYDIR/pkgconfig:$PKG_CONFIG_PATH

	# export
	export OSPL_URI

	# clean
	unset GAIA_THIRD_PARTY_OSPL_ROOT
	unset GAIA_THIRD_PARTY_OSPL_LIBRARYDIR
	unset GAIA_THIRD_PARTY_OSPL_INCLUDEDIR
	unset GAIA_THIRD_PARTY_OSPL_BINARYDIR

fi

#== EOF
