#!/bin/bash

#
# GAIA : required LABSIM ground software ecosystem
# Copyright (C) 2012-2016  Nawfel KINANI
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.
# If not, see <http://www.gnu.org/licenses/>.
#


# detail
GAIA_ECOSYSTEM_DETAIL+="\n\t+--[ Third_party : <Development> ]"

###################################################################
# Make
###

if [ "${GAIA_THIRD_PARTY_MAKE_FOUND}" = true ]; then

	# internal
	GAIA_THIRD_PARTY_MAKE_ROOT=$GAIA_THIRD_PARTY_HOME/make-$GAIA_THIRD_PARTY_MAKE_VERSION
	GAIA_THIRD_PARTY_MAKE_BINARYDIR=$GAIA_THIRD_PARTY_MAKE_ROOT/bin
	GAIA_THIRD_PARTY_MAKE_LIBRARYDIR=$GAIA_THIRD_PARTY_MAKE_ROOT/lib
	GAIA_THIRD_PARTY_MAKE_INCLUDEDIR=$GAIA_THIRD_PARTY_MAKE_ROOT/include

	# info
	GAIA_ECOSYSTEM_DETAIL+="\n\t|\t* make v.$GAIA_THIRD_PARTY_MAKE_VERSION"

	# env
	CPATH=$GAIA_THIRD_PARTY_MAKE_INCLUDEDIR:$CPATH
	PATH=$GAIA_THIRD_PARTY_MAKE_BINARYDIR:$PATH
	LD_LIBRARY_PATH=$GAIA_THIRD_PARTY_MAKE_LIBRARYDIR:$LD_LIBRARY_PATH

	# clean
	unset GAIA_THIRD_PARTY_MAKE_ROOT
	unset GAIA_THIRD_PARTY_MAKE_LIBRARYDIR
	unset GAIA_THIRD_PARTY_MAKE_INCLUDEDIR
	unset GAIA_THIRD_PARTY_MAKE_BINARYDIR

fi

###################################################################
# PERL
###

if [ "${GAIA_THIRD_PARTY_PERL_FOUND}" = true ]; then

	# internal
	GAIA_THIRD_PARTY_PERL_ROOT=$GAIA_THIRD_PARTY_HOME/perl-$GAIA_THIRD_PARTY_PERL_VERSION
	GAIA_THIRD_PARTY_PERL_BINARYDIR=$GAIA_THIRD_PARTY_PERL_ROOT/bin
	GAIA_THIRD_PARTY_PERL_LIBRARYDIR=$GAIA_THIRD_PARTY_PERL_ROOT/lib/$GAIA_THIRD_PARTY_PERL_VERSION:$GAIA_THIRD_PARTY_PERL_ROOT/lib/site_perl/$GAIA_THIRD_PARTY_PERL_VERSION

	# info
	GAIA_ECOSYSTEM_DETAIL+="\n\t|\t* perl v.$GAIA_THIRD_PARTY_PERL_VERSION"

	# env
	PERL5LIB=$GAIA_THIRD_PARTY_PERL_LIBRARYDIR
	PATH=$GAIA_THIRD_PARTY_PERL_BINARYDIR:$PATH
	LD_LIBRARY_PATH=$GAIA_THIRD_PARTY_PERL_LIBRARYDIR:$LD_LIBRARY_PATH

	# export
	export PERL5LIB

	# clean
	unset GAIA_THIRD_PARTY_PERL_ROOT
	unset GAIA_THIRD_PARTY_PERL_LIBRARYDIR
	unset GAIA_THIRD_PARTY_PERL_BINARYDIR

fi

###################################################################
# ARES
###

if [ "${GAIA_THIRD_PARTY_ARES_FOUND}" = true ]; then

	# internal
	GAIA_THIRD_PARTY_ARES_ROOT=$GAIA_THIRD_PARTY_HOME/ares-$GAIA_THIRD_PARTY_ARES_VERSION
	GAIA_THIRD_PARTY_ARES_LIBRARYDIR=$GAIA_THIRD_PARTY_ARES_ROOT/lib
	GAIA_THIRD_PARTY_ARES_INCLUDEDIR=$GAIA_THIRD_PARTY_ARES_ROOT/include
	GAIA_THIRD_PARTY_ARES_BINARYDIR=$GAIA_THIRD_PARTY_ARES_ROOT/bin

	# info
	GAIA_ECOSYSTEM_DETAIL+="\n\t|\t* C-Ares v.$GAIA_THIRD_PARTY_ARES_VERSION"

	# env
	CPATH=$GAIA_THIRD_PARTY_ARES_INCLUDEDIR:$CPATH
	PATH=$GAIA_THIRD_PARTY_ARES_BINARYDIR:$PATH
	LD_LIBRARY_PATH=$GAIA_THIRD_PARTY_ARES_LIBRARYDIR:$LD_LIBRARY_PATH
	PKG_CONFIG_PATH=$GAIA_THIRD_PARTY_ARES_LIBRARYDIR/pkgconfig:$PKG_CONFIG_PATH

	# clean
	unset GAIA_THIRD_PARTY_ARES_ROOT
	unset GAIA_THIRD_PARTY_ARES_LIBRARYDIR
	unset GAIA_THIRD_PARTY_ARES_INCLUDEDIR
	unset GAIA_THIRD_PARTY_ARES_BINARYDIR

fi

###################################################################
# OPENSSL
###

if [ "${GAIA_THIRD_PARTY_OPENSSL_FOUND}" = true ]; then

	# internal
	GAIA_THIRD_PARTY_OPENSSL_ROOT=$GAIA_THIRD_PARTY_HOME/openssl-$GAIA_THIRD_PARTY_OPENSSL_VERSION
	GAIA_THIRD_PARTY_OPENSSL_LIBRARYDIR=$GAIA_THIRD_PARTY_OPENSSL_ROOT/lib
	GAIA_THIRD_PARTY_OPENSSL_INCLUDEDIR=$GAIA_THIRD_PARTY_OPENSSL_ROOT/include
	GAIA_THIRD_PARTY_OPENSSL_BINARYDIR=$GAIA_THIRD_PARTY_OPENSSL_ROOT/bin

	# info
	GAIA_ECOSYSTEM_DETAIL+="\n\t|\t* OpenSSL v.$GAIA_THIRD_PARTY_OPENSSL_VERSION"

	# env
	CPATH=$GAIA_THIRD_PARTY_OPENSSL_INCLUDEDIR:$CPATH
	PATH=$GAIA_THIRD_PARTY_OPENSSL_BINARYDIR:$PATH
	LD_LIBRARY_PATH=$GAIA_THIRD_PARTY_OPENSSL_LIBRARYDIR:$LD_LIBRARY_PATH
	PKG_CONFIG_PATH=$GAIA_THIRD_PARTY_OPENSSL_LIBRARYDIR/pkgconfig:$PKG_CONFIG_PATH

	# clean
	unset GAIA_THIRD_PARTY_OPENSSL_ROOT
	unset GAIA_THIRD_PARTY_OPENSSL_LIBRARYDIR
	unset GAIA_THIRD_PARTY_OPENSSL_INCLUDEDIR
	unset GAIA_THIRD_PARTY_OPENSSL_BINARYDIR

fi

###################################################################
# GIT
###

if [ "${GAIA_THIRD_PARTY_GIT_FOUND}" = true ]; then

	# internal
	GAIA_THIRD_PARTY_GIT_ROOT=$GAIA_THIRD_PARTY_HOME/git-$GAIA_THIRD_PARTY_GIT_VERSION
	GAIA_THIRD_PARTY_GIT_BINARYDIR=$GAIA_THIRD_PARTY_GIT_ROOT/bin

	# info
	GAIA_ECOSYSTEM_DETAIL+="\n\t|\t* Git v.$GAIA_THIRD_PARTY_GIT_VERSION"

	# env
	PATH=$GAIA_THIRD_PARTY_GIT_BINARYDIR:$PATH

	# clean
	unset GAIA_THIRD_PARTY_GIT_ROOT
	unset GAIA_THIRD_PARTY_GIT_BINARYDIR

fi

###################################################################
# CMake/Ctest/CPack
###

if [ "${GAIA_THIRD_PARTY_CMAKE_FOUND}" = true ]; then

	# unload any previous cmake versions if DSI host
	if [ "${GAIA_FOUND_DSI_HOST}" = true ]; then

		module unload cmake

	fi

	# internal
	GAIA_THIRD_PARTY_CMAKE_ROOT=$GAIA_THIRD_PARTY_HOME/cmake-$GAIA_THIRD_PARTY_CMAKE_VERSION
	GAIA_THIRD_PARTY_CMAKE_BINARYDIR=$GAIA_THIRD_PARTY_CMAKE_ROOT/bin
	GAIA_THIRD_PARTY_CMAKE_MODULE_PATH=$GAIA_THIRD_PARTY_CMAKE_ROOT/share/cmake-$GAIA_THIRD_PARTY_CMAKE_MAJ_VER.$GAIA_THIRD_PARTY_CMAKE_MIN_VER/Modules

	# info
	GAIA_ECOSYSTEM_DETAIL+="\n\t|\t* cmake v.$GAIA_THIRD_PARTY_CMAKE_VERSION"

	# env
	CMAKE_MODULE_PATH=$GAIA_THIRD_PARTY_CMAKE_MODULE_PATH
	PATH=$GAIA_THIRD_PARTY_CMAKE_BINARYDIR:$PATH

	# export
	export CMAKE_MODULE_PATH

	# clean
	unset GAIA_THIRD_PARTY_CMAKE_ROOT
	unset GAIA_THIRD_PARTY_CMAKE_MODULE_PATH
	unset GAIA_THIRD_PARTY_CMAKE_BINARYDIR

fi

###################################################################
# Xerces-C++
###

if [ "${GAIA_THIRD_PARTY_XERCES_FOUND}" = true ]; then

	# internal
	GAIA_THIRD_PARTY_XERCES_ROOT=$GAIA_THIRD_PARTY_HOME/xerces-$GAIA_THIRD_PARTY_XERCES_VERSION
	GAIA_THIRD_PARTY_XERCES_BINARYDIR=$GAIA_THIRD_PARTY_XERCES_ROOT/bin
	GAIA_THIRD_PARTY_XERCES_LIBRARYDIR=$GAIA_THIRD_PARTY_XERCES_ROOT/lib
	GAIA_THIRD_PARTY_XERCES_INCLUDEDIR=$GAIA_THIRD_PARTY_XERCES_ROOT/include

	# info
	GAIA_ECOSYSTEM_DETAIL+="\n\t|\t* xerces-c++ v.$GAIA_THIRD_PARTY_XERCES_VERSION"

	# env
	CPATH=$GAIA_THIRD_PARTY_XERCES_INCLUDEDIR:$CPATH
	PATH=$GAIA_THIRD_PARTY_XERCES_BINARYDIR:$PATH
	LD_LIBRARY_PATH=$GAIA_THIRD_PARTY_XERCES_LIBRARYDIR:$LD_LIBRARY_PATH
	PKG_CONFIG_PATH=$GAIA_THIRD_PARTY_XERCES_LIBRARYDIR/pkgconfig:$PKG_CONFIG_PATH

	# clean
	unset GAIA_THIRD_PARTY_XERCES_ROOT
	unset GAIA_THIRD_PARTY_XERCES_LIBRARYDIR
	unset GAIA_THIRD_PARTY_XERCES_INCLUDEDIR
	unset GAIA_THIRD_PARTY_XERCES_BINARYDIR

fi

###################################################################
# Doxygen
###

if [ "${GAIA_THIRD_PARTY_DOXYGEN_FOUND}" = true ]; then

	# internal
	GAIA_THIRD_PARTY_DOXYGEN_ROOT=$GAIA_THIRD_PARTY_HOME/doxygen-$GAIA_THIRD_PARTY_DOXYGEN_VERSION
	GAIA_THIRD_PARTY_DOXYGEN_BINARYDIR=$GAIA_THIRD_PARTY_DOXYGEN_ROOT/bin

	# info
	GAIA_ECOSYSTEM_DETAIL+="\n\t|\t* doxygen v.$GAIA_THIRD_PARTY_DOXYGEN_VERSION"

	# env
	PATH=$GAIA_THIRD_PARTY_DOXYGEN_BINARYDIR:$PATH

	# clean
	unset GAIA_THIRD_PARTY_DOXYGEN_ROOT
	unset GAIA_THIRD_PARTY_DOXYGEN_BINARYDIR

fi

###################################################################
# Boost
###

if [ "${GAIA_THIRD_PARTY_BOOST_FOUND}" = true ]; then

	# internal
	GAIA_THIRD_PARTY_BOOST_ROOT=$GAIA_THIRD_PARTY_HOME/boost-$GAIA_THIRD_PARTY_BOOST_VERSION
	GAIA_THIRD_PARTY_BOOST_LIBRARYDIR=$GAIA_THIRD_PARTY_BOOST_ROOT/lib
	GAIA_THIRD_PARTY_BOOST_INCLUDEDIR=$GAIA_THIRD_PARTY_BOOST_ROOT/include

	# info
	GAIA_ECOSYSTEM_DETAIL+="\n\t|\t* boost v.$GAIA_THIRD_PARTY_BOOST_VERSION"

	# env
	CPATH=$GAIA_THIRD_PARTY_BOOST_INCLUDEDIR:$CPATH
	LD_LIBRARY_PATH=$GAIA_THIRD_PARTY_BOOST_LIBRARYDIR:$LD_LIBRARY_PATH
	BOOST_ROOT=$GAIA_THIRD_PARTY_BOOST_ROOT

	# export
	export BOOST_ROOT

	# clean
	unset GAIA_THIRD_PARTY_BOOST_ROOT
	unset GAIA_THIRD_PARTY_BOOST_LIBRARYDIR
	unset GAIA_THIRD_PARTY_BOOST_INCLUDEDIR

fi

###################################################################
# LLVM
###

if [ "${GAIA_THIRD_PARTY_LLVM_FOUND}" = true ]; then

	# internal
	GAIA_THIRD_PARTY_LLVM_ROOT=$GAIA_THIRD_PARTY_HOME/llvm-$GAIA_THIRD_PARTY_LLVM_VERSION
	GAIA_THIRD_PARTY_LLVM_INCLUDEDIR=$GAIA_THIRD_PARTY_LLVM_ROOT/include
	GAIA_THIRD_PARTY_LLVM_LIBRARYDIR=$GAIA_THIRD_PARTY_LLVM_ROOT/lib
	GAIA_THIRD_PARTY_LLVM_BINARYDIR=$GAIA_THIRD_PARTY_LLVM_ROOT/bin

	# info
	GAIA_ECOSYSTEM_DETAIL+="\n\t|\t* LLVM project (Clang) v.$GAIA_THIRD_PARTY_LLVM_VERSION"

	# env
	LLVM_INSTALL_DIR=$GAIA_THIRD_PARTY_LLVM_ROOT
	CPATH=$GAIA_THIRD_PARTY_LLVM_INCLUDEDIR:$CPATH
	PATH=$GAIA_THIRD_PARTY_LLVM_BINARYDIR:$PATH
	LD_LIBRARY_PATH=$GAIA_THIRD_PARTY_LLVM_LIBRARYDIR:$LD_LIBRARY_PATH

	# export
	export LLVM_INSTALL_DIR

	# clean
	unset GAIA_THIRD_PARTY_LLVM_ROOT
	unset GAIA_THIRD_PARTY_LLVM_LIBRARYDIR
	unset GAIA_THIRD_PARTY_LLVM_INCLUDEDIR
	unset GAIA_THIRD_PARTY_LLVM_BINARYDIR

fi

#== EOF
