#!/bin/bash

#
# GAIA : required LABSIM ground software ecosystem
# Copyright (C) 2012-2016  Nawfel KINANI
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; see the file COPYING.
# If not, see <http://www.gnu.org/licenses/>.
#


# detail
GAIA_DISTRIBUTION_DETAIL+="\n\t+--[ Third_party : <Virtual Reality (VR)> ]"

###################################################################
# HID API
###

if [ "${GAIA_THIRD_PARTY_HIDAPI_FOUND}" = true ]; then

	# internal
	GAIA_THIRD_PARTY_HIDAPI_ROOT=$GAIA_THIRD_PARTY_HOME/hidapi-$GAIA_THIRD_PARTY_HIDAPI_VERSION
	GAIA_THIRD_PARTY_HIDAPI_LIBRARYDIR=$GAIA_THIRD_PARTY_HIDAPI_ROOT/lib
	GAIA_THIRD_PARTY_HIDAPI_INCLUDEDIR=$GAIA_THIRD_PARTY_HIDAPI_ROOT/include

	# info
	GAIA_DISTRIBUTION_DETAIL+="\n\t|\t* hidapi v.$GAIA_THIRD_PARTY_HIDAPI_VERSION"

	# env
	CPATH=$GAIA_THIRD_PARTY_HIDAPI_INCLUDEDIR:$CPATH
	LD_LIBRARY_PATH=$GAIA_THIRD_PARTY_HIDAPI_LIBRARYDIR:$LD_LIBRARY_PATH

	# clean
	unset GAIA_THIRD_PARTY_HIDAPI_ROOT
	unset GAIA_THIRD_PARTY_HIDAPI_LIBRARYDIR
	unset GAIA_THIRD_PARTY_HIDAPI_INCLUDEDIR

fi

###################################################################
# JSON CPP
###

if [ "${GAIA_THIRD_PARTY_JSONCPP_FOUND}" = true ]; then

	# internal
	GAIA_THIRD_PARTY_JSONCPP_ROOT=$GAIA_THIRD_PARTY_HOME/jsoncpp-$GAIA_THIRD_PARTY_JSONCPP_VERSION
	GAIA_THIRD_PARTY_JSONCPP_LIBRARYDIR=$GAIA_THIRD_PARTY_JSONCPP_ROOT/lib
	GAIA_THIRD_PARTY_JSONCPP_INCLUDEDIR=$GAIA_THIRD_PARTY_JSONCPP_ROOT/include

	# info
	GAIA_DISTRIBUTION_DETAIL+="\n\t|\t* jsonCPP v.$GAIA_THIRD_PARTY_JSONCPP_VERSION"

	# env
	CPATH=$GAIA_THIRD_PARTY_JSONCPP_INCLUDEDIR:$CPATH
	LD_LIBRARY_PATH=$GAIA_THIRD_PARTY_JSONCPP_LIBRARYDIR:$LD_LIBRARY_PATH

	# clean
	unset GAIA_THIRD_PARTY_JSONCPP_ROOT
	unset GAIA_THIRD_PARTY_JSONCPP_LIBRARYDIR
	unset GAIA_THIRD_PARTY_JSONCPP_INCLUDEDIR

fi

###################################################################
# OSVR - lib functionality
###

if [ "${GAIA_THIRD_PARTY_OSVR_LIBFUNCTIONALITY_FOUND}" = true ]; then

	# internal
	GAIA_THIRD_PARTY_OSVR_LIBFUNCTIONALITY_ROOT=$GAIA_THIRD_PARTY_HOME/osvr-libfunctionality-$GAIA_THIRD_PARTY_OSVR_LIBFUNCTIONALITY_VERSION
	GAIA_THIRD_PARTY_OSVR_LIBFUNCTIONALITY_LIBRARYDIR=$GAIA_THIRD_PARTY_OSVR_LIBFUNCTIONALITY_ROOT/lib64
	GAIA_THIRD_PARTY_OSVR_LIBFUNCTIONALITY_INCLUDEDIR=$GAIA_THIRD_PARTY_OSVR_LIBFUNCTIONALITY_ROOT/include
	GAIA_THIRD_PARTY_OSVR_LIBFUNCTIONALITY_BINARYDIR=$GAIA_THIRD_PARTY_OSVR_LIBFUNCTIONALITY_ROOT/bin

	# info
	GAIA_DISTRIBUTION_DETAIL+="\n\t|\t* OSVR-libfunctionality v.$GAIA_THIRD_PARTY_OSVR_LIBFUNCTIONALITY_VERSION"

	# env
	CPATH=$GAIA_THIRD_PARTY_OSVR_LIBFUNCTIONALITY_INCLUDEDIR:$CPATH
	PATH=$GAIA_THIRD_PARTY_OSVR_LIBFUNCTIONALITY_BINARYDIR:$PATH
	LD_LIBRARY_PATH=$GAIA_THIRD_PARTY_OSVR_LIBFUNCTIONALITY_LIBRARYDIR:$LD_LIBRARY_PATH

	# clean
	unset GAIA_THIRD_PARTY_OSVR_LIBFUNCTIONALITY_ROOT
	unset GAIA_THIRD_PARTY_OSVR_LIBFUNCTIONALITY_LIBRARYDIR
	unset GAIA_THIRD_PARTY_OSVR_LIBFUNCTIONALITY_INCLUDEDIR
	unset GAIA_THIRD_PARTY_OSVR_LIBFUNCTIONALITY_BINARYDIR

fi

###################################################################
# OSVR - core
###

if [ "${GAIA_THIRD_PARTY_OSVR_CORE_FOUND}" = true ]; then

	# internal
	GAIA_THIRD_PARTY_OSVR_CORE_ROOT=$GAIA_THIRD_PARTY_HOME/osvr-core-$GAIA_THIRD_PARTY_OSVR_CORE_VERSION
	GAIA_THIRD_PARTY_OSVR_CORE_LIBRARYDIR=$GAIA_THIRD_PARTY_OSVR_CORE_ROOT/lib64
	GAIA_THIRD_PARTY_OSVR_CORE_INCLUDEDIR=$GAIA_THIRD_PARTY_OSVR_CORE_ROOT/include
	GAIA_THIRD_PARTY_OSVR_CORE_BINARYDIR=$GAIA_THIRD_PARTY_OSVR_CORE_ROOT/bin

	# info
	GAIA_DISTRIBUTION_DETAIL+="\n\t|\t* OSVR-core v.$GAIA_THIRD_PARTY_OSVR_CORE_VERSION"

	# env
	CPATH=$GAIA_THIRD_PARTY_OSVR_CORE_INCLUDEDIR:$CPATH
	PATH=$GAIA_THIRD_PARTY_OSVR_CORE_BINARYDIR:$PATH
	LD_LIBRARY_PATH=$GAIA_THIRD_PARTY_OSVR_CORE_LIBRARYDIR:$LD_LIBRARY_PATH

	# clean
	unset GAIA_THIRD_PARTY_OSVR_CORE_ROOT
	unset GAIA_THIRD_PARTY_OSVR_CORE_LIBRARYDIR
	unset GAIA_THIRD_PARTY_OSVR_CORE_INCLUDEDIR
	unset GAIA_THIRD_PARTY_OSVR_CORE_BINARYDIR

fi

###################################################################
# OSVR - display
###

if [ "${GAIA_THIRD_PARTY_OSVR_DISPLAY_FOUND}" = true ]; then

	# internal
	GAIA_THIRD_PARTY_OSVR_DISPLAY_ROOT=$GAIA_THIRD_PARTY_HOME/osvr-display-$GAIA_THIRD_PARTY_OSVR_DISPLAY_VERSION
	GAIA_THIRD_PARTY_OSVR_DISPLAY_LIBRARYDIR=$GAIA_THIRD_PARTY_OSVR_DISPLAY_ROOT/lib64
	GAIA_THIRD_PARTY_OSVR_DISPLAY_INCLUDEDIR=$GAIA_THIRD_PARTY_OSVR_DISPLAY_ROOT/include
	GAIA_THIRD_PARTY_OSVR_DISPLAY_BINARYDIR=$GAIA_THIRD_PARTY_OSVR_DSIPLAY_ROOT/bin

	# info
	GAIA_DISTRIBUTION_DETAIL+="\n\t|\t* OSVR-display v.$GAIA_THIRD_PARTY_OSVR_DISPLAY_VERSION"

	# env
	CPATH=$GAIA_THIRD_PARTY_OSVR_DISPLAY_INCLUDEDIR:$CPATH
	PATH=$GAIA_THIRD_PARTY_OSVR_DISPLAY_BINARYDIR:$PATH
	LD_LIBRARY_PATH=$GAIA_THIRD_PARTY_OSVR_DISPLAY_LIBRARYDIR:$LD_LIBRARY_PATH

	# clean
	unset GAIA_THIRD_PARTY_OSVR_DISPLAY_ROOT
	unset GAIA_THIRD_PARTY_OSVR_DISPLAY_LIBRARYDIR
	unset GAIA_THIRD_PARTY_OSVR_DISPLAY_INCLUDEDIR
	unset GAIA_THIRD_PARTY_OSVR_DISPLAY_BINARYDIR

fi

#== EOF
