#!/bin/bash

#######################
# ELIPS Dev Environment config
#
# Ce fichier est inclu depuis /etc/profile au demarrage de la machine
# ou alors par le fichier .bashrc lors de l'ouverture d'un terminal
#
# 07/02/12 - Kinani Nawfel
#######################

###
# Admin file recovery
###
# Ces variables servent pour la construction des chemins relatif au types de l'environment de dev utilisé -> type foo/src seulement ou foo/branch/src
# Le path relatif a ELIPSHOME pour recuperer /dev/ (!! pas de slash de début et de fin)
export ELIPS_RELATIVE=".."
# Le path relatif a chaque sous-projet (!! pas de slash de début et de fin)
export ELIPS_SUBDIR=""

###
# ELIPS Dir
###
source "/home/elips/dev/ELIPS/gener.macro"

###
# OSG Dir
###
export OSG_DIR="/home/elips/Progiciels/OSG/"

###
# Boost Dir
###
export BOOST_ROOT="/home/elips/Progiciels/boost_1_45_0/"
export BOOST_INCLUDEDIR="/home/elips/Progiciels/boost_1_45_0/"
export BOOST_LIBRARYDIR="/home/elips/Progiciels/boost_1_45_0/stage/lib/"

###
# QT Dir
###

###
# Lib-embeded Dir
###

#######################
