#!/bin/bash

#######################
# ELIPS 2010 Environment config
#
# Ce fichier est inclu depuis /etc/profile au demarrage de la machine
# ou alors par le fichier .bashrc lors de l'ouverture d'un terminal
#
# 07/02/12 - Kinani Nawfel
#######################

###
# ELIPS Dir
###
source "/home/elips/ELIPS2010/gener.macro"

###
# OSG Dir
###
export OSG_DIR="/home/elips/Progiciels/OSG/"

###
# Boost Dir
###
export BOOST_ROOT="/home/elips/Progiciels/boost_1_45_0/"
export BOOST_INCLUDEDIR="/home/elips/Progiciels/boost_1_45_0/"
export BOOST_LIBRARYDIR="/home/elips/Progiciels/boost_1_45_0/stage/lib/"

#######################
