#!/bin/bash

#######################
# global environment config
#
# Ce fichier est inclu depuis /etc/profile au demarrage de la machine
# ou alors par le fichier .bashrc lors de l'ouverture d'un terminal
#
# 07/02/12 - Kinani Nawfel
#######################

###
# Informations
###
function infoelips ()
{
	echo "=========================================================================="
	echo " Environment de dev courant :" $ELIPS_CURRENT_DIST
	echo "=========================================================================="
	
	exit 0
}

###
# On check l'existance du script de changement de l'environment ELIPS
###
if [ -f /home/elips/dev_conf/scripts/ELIPS_switch.sh ]; then 
	alias switchelips="/home/elips/dev_conf/scripts/ELIPS_switch.sh"
fi


###
# Progiciel Home path
### 
PRO_HOME=/home/elips/Progiciels

###
# OSG Dir
###
OSG_DIR=$PRO_HOME/OSG/

###
# Boost Dir
###
BOOST_ROOT=$PRO_HOME/boost_1_45_0/
BOOST_INCLUDEDIR=$PRO_HOME/boost_1_45_0/
BOOST_LIBRARYDIR=$PRO_HOME/boost_1_45_0/stage/lib/

###
# TAO - OpenFusionTAO
###
# ACE ROOT - The home of the ADAPTIVE Communication Environment
# TAO ROOT - The home of The Ace Orb
# TAO IDL - The Interface Definition Language compiler 
###
ACE_ROOT=$PRO_HOME/OpenFusionTAO
TAO_ROOT=$PRO_HOME/OpenFusionTAO
TAO_IDL=$PRO_HOME/OpenFusionTAO/bin/tao_idl

###
# OpenSpliceDDS
###
# OSPL ROOT - The home of the Open SPLice global project
# OSPL HDE ROOT - The home of the OSPL project Host Development Environment (Configured)
# OSPL RTS ROOT - The home of the OSPL project RunTime Sofware (Configured)
# We source the release.com file generated which contain all the variable definition
###
OSPL_ROOT=$PRO_HOME/OpenSpliceDDS
OSPL_RTS_ROOT=$PRO_HOME/OpenSpliceDDS/RTS/x86_64.linux2.6-dev
OSPL_HDE_ROOT=$PRO_HOME/OpenSpliceDDS/HDE/x86_64.linux2.6-dev
OSPL_LOGPATH=$PRO_HOME/OpenSpliceDDS/log

###
# Java Home
###
JAVA_HOME="/home/elips/dev_env/jre/jre1.6.0_31/"

###
# Global Variable
###
PATH=$PATH:$TAO_ROOT/bin
LD_LIBRARY_PATH=$TAO_ROOT/lib:/lib/:/usr/lib/:$LD_LIBRARY_PATH
INSLIB=$TAO_ROOT/lib:$INSLIB

###
# Export & sourcing
###
export OSG_DIR BOOST_ROOT BOOST_INCLUDEDIR BOOST_LIBRARYDIR ACE_ROOT TAO_ROOT TAO_IDL OSPL_ROOT OSPL_RTS_ROOT OSPL_HDE_ROOT OSPL_LOGPATH JAVA_HOME PATH LD_LIBRARY_PATH INSLIB
source "$OSPL_HDE_ROOT/release.com"

# On active le traitement des commandes tierces avec xhost
xhost + > /dev/null

#######################
